'use strict';
// Comprehensive bank catalog — PK / UK / UAE / US / intl.
// Single source of truth for domain → logo. Runtime uses local assets/banks/{slug}.png.

const BANK_CATALOG = {
  // ── Pakistan ──────────────────────────────────────────────
  'HBL': 'hbl.com',
  'Habib Bank': 'hbl.com',
  'HBL Bank': 'hbl.com',
  'UBL': 'ubl.com.pk',
  'United Bank': 'ubl.com.pk',
  'United Bank Limited': 'ubl.com.pk',
  'MCB': 'mcb.com.pk',
  'MCB Bank': 'mcb.com.pk',
  'ABL': 'abl.com',
  'Allied Bank': 'abl.com',
  'Allied': 'abl.com',
  'NBP': 'nbp.com.pk',
  'National Bank': 'nbp.com.pk',
  'National Bank of Pakistan': 'nbp.com.pk',
  'Meezan': 'meezanbank.com',
  'Meezan Bank': 'meezanbank.com',
  'Faysal': 'faysalbank.com',
  'Faysal Bank': 'faysalbank.com',
  'Askari': 'askaribank.com.pk',
  'Askari Bank': 'askaribank.com.pk',
  'Bank Alfalah': 'bankalfalah.com',
  'Alfalah': 'bankalfalah.com',
  'Bank Al Habib': 'bankalhabib.com',
  'BAHL': 'bankalhabib.com',
  'Habib Metro': 'habibmetro.com',
  'Habib Metro Bank': 'habibmetro.com',
  'Bank Islami': 'bankislami.com.pk',
  'Islami': 'bankislami.com.pk',
  'Silkbank': 'silkbank.com.pk',
  'Silk Bank': 'silkbank.com.pk',
  'Summit Bank': 'summitbank.com.pk',
  'Summit': 'summitbank.com.pk',
  'Soneri': 'soneribank.com',
  'Soneri Bank': 'soneribank.com',
  'JS Bank': 'jsbl.com',
  'JS': 'jsbl.com',
  'Bank of Punjab': 'bop.com.pk',
  'BOP': 'bop.com.pk',
  'Standard Chartered PK': 'sc.com',
  'Standard Chartered': 'sc.com',
  'Samba Bank': 'samba.com.pk',
  'Dubai Islamic Bank PK': 'dibpak.com',
  'Al Baraka': 'albaraka.com.pk',
  'Bank AlBaraka': 'albaraka.com.pk',
  'First Women Bank': 'fwbl.com.pk',
  'FWBL': 'fwbl.com.pk',
  'Sindh Bank': 'sindhbank.com.pk',
  'The Bank of Khyber': 'bok.com.pk',
  'BOK': 'bok.com.pk',
  'Industrial Development Bank': 'idbp.com.pk',
  'Zarai Taraqiati': 'ztbl.com.pk',
  'ZTBL': 'ztbl.com.pk',
  'Punjab Provincial Cooperative Bank': 'ppcb.com.pk',
  'Khushhali Microfinance': 'khushhalibank.com.pk',
  'Telenor Microfinance': 'telenorbank.pk',
  'U Microfinance': 'ubank.com.pk',
  'Mobilink Microfinance': 'jazzcash.com.pk',
  'Apna Microfinance': 'apnabank.com.pk',
  'NRSP Microfinance': 'nrspbank.com',
  'JazzCash': 'jazzcash.com.pk',
  'Jazz Cash': 'jazzcash.com.pk',
  'EasyPaisa': 'easypaisa.com.pk',
  'NayaPay': 'nayapay.com',
  'SadaPay': 'sadapay.com',
  'Sadapay': 'sadapay.com',
  'Zindigi': 'zindigi.com',
  'Bykea Pay': 'bykea.com',
  'Keepa': 'keepa.pk',

  // ── UK ────────────────────────────────────────────────────
  'Barclays': 'barclays.co.uk',
  'Barclaycard': 'barclays.co.uk',
  'Lloyds': 'lloydsbank.com',
  'Lloyds Bank': 'lloydsbank.com',
  'NatWest': 'natwest.com',
  'Nat West': 'natwest.com',
  'HSBC': 'hsbc.co.uk',
  'HSBC UK': 'hsbc.co.uk',
  'Santander': 'santander.co.uk',
  'Santander UK': 'santander.co.uk',
  'Nationwide': 'nationwide.co.uk',
  'Monzo': 'monzo.com',
  'Starling': 'starlingbank.com',
  'Starling Bank': 'starlingbank.com',
  'Revolut': 'revolut.com',
  'Wise': 'wise.com',
  'Monese': 'monese.com',
  'Halifax': 'halifax.co.uk',
  'First Direct': 'firstdirect.com',
  'Metro Bank': 'metrobankonline.co.uk',
  'Metro': 'metrobankonline.co.uk',
  'TSB': 'tsb.co.uk',
  'TSB Bank': 'tsb.co.uk',
  'Co-op': 'co-operativebank.co.uk',
  'Co-operative Bank': 'co-operativebank.co.uk',
  'Coop': 'co-operativebank.co.uk',
  'Virgin Money': 'virginmoney.com',
  'Virgin': 'virginmoney.com',
  'Chase UK': 'chase.co.uk',
  'Atom': 'atombank.co.uk',
  'Atom Bank': 'atombank.co.uk',
  'Al Rayan Bank': 'alrayanbank.co.uk',
  'Coutts': 'coutts.com',
  'Schroders Personal Wealth': 'schroderspersonalwealth.co.uk',
  'Investec': 'investec.com',
  'Shawbrook': 'shawbrook.co.uk',
  'Shawbrook Bank': 'shawbrook.co.uk',
  'Aldermore': 'aldermore.co.uk',
  'Tandem': 'tandem.co.uk',
  'Tandem Bank': 'tandem.co.uk',
  'Marcus': 'marcus.co.uk',
  'Marcus by Goldman Sachs': 'marcus.co.uk',
  'Smile': 'smile.co.uk',
  'Yorkshire Bank': 'ybonline.co.uk',
  'Clydesdale': 'cbonline.co.uk',
  'Bank of Scotland': 'bankofscotland.co.uk',
  'Royal Bank of Scotland': 'rbs.co.uk',
  'RBS': 'rbs.co.uk',
  'Ulster Bank': 'ulsterbank.co.uk',
  'Danske Bank UK': 'danskebank.co.uk',
  'Handelsbanken UK': 'handelsbanken.co.uk',
  'Tide': 'tide.co',
  'Anna Money': 'anna.money',
  'Cashplus': 'cashplus.com',
  'Curve': 'curve.com',
  'Chip': 'getchip.uk',
  'Plum': 'withplum.com',
  'Moneybox': 'moneyboxapp.com',
  'Trading 212': 'trading212.com',
  'Hargreaves Lansdown': 'hl.co.uk',
  'AJ Bell': 'ajbell.co.uk',
  'Interactive Investor': 'ii.co.uk',
  'Vanguard UK': 'vanguardinvestor.co.uk',

  // ── UAE ───────────────────────────────────────────────────
  'Emirates NBD': 'emiratesnbd.com',
  'ENBD': 'emiratesnbd.com',
  'Emirates': 'emiratesnbd.com',
  'FAB': 'bankfab.com',
  'First Abu Dhabi Bank': 'bankfab.com',
  'ADCB': 'adcb.com',
  'Abu Dhabi Commercial Bank': 'adcb.com',
  'RAKBank': 'rakbank.ae',
  'RAK Bank': 'rakbank.ae',
  'RAKBANK': 'rakbank.ae',
  'Mashreq': 'mashreq.com',
  'Mashreq Bank': 'mashreq.com',
  'DIB': 'dib.ae',
  'Dubai Islamic Bank': 'dib.ae',
  'ADIB': 'adib.ae',
  'Abu Dhabi Islamic Bank': 'adib.ae',
  'CBD': 'cbd.ae',
  'Commercial Bank of Dubai': 'cbd.ae',
  'Noor Bank': 'emiratesnbd.com',
  'Noor': 'emiratesnbd.com',
  'Wio': 'wio.io',
  'Wio Bank': 'wio.io',
  'Liv': 'liv.ae',
  'Liv.': 'liv.ae',
  'HSBC UAE': 'hsbc.ae',
  'Standard Chartered UAE': 'sc.com',
  'Citibank UAE': 'citibank.ae',
  'Ajman Bank': 'ajmanbank.ae',
  'United Arab Bank': 'uab.ae',
  'UAB': 'uab.ae',
  'National Bank of Fujairah': 'nbf.ae',
  'NBF': 'nbf.ae',
  'Bank of Sharjah': 'bankofsharjah.com',
  'Sharjah Islamic Bank': 'sib.ae',
  'SIB': 'sib.ae',
  'Al Hilal Bank': 'alhilalbank.ae',
  'Emirates Islamic': 'emiratesislamic.ae',
  'EI': 'emiratesislamic.ae',
  'Dubai Bank': 'dubaibank.ae',
  'Finance House': 'financehouse.ae',
  'Ruya': 'ruya.ae',

  // ── US / International ────────────────────────────────────
  'Chase': 'chase.com',
  'Chase Bank': 'chase.com',
  'Bank of America': 'bankofamerica.com',
  'BofA': 'bankofamerica.com',
  'Wells Fargo': 'wellsfargo.com',
  'Wells': 'wellsfargo.com',
  'Citi': 'citibank.com',
  'Citibank': 'citibank.com',
  'Citi Bank': 'citibank.com',
  'Amex': 'americanexpress.com',
  'American Express': 'americanexpress.com',
  'JPMorgan': 'jpmorgan.com',
  'JP Morgan': 'jpmorgan.com',
  'Deutsche Bank': 'db.com',
  'Deutsche': 'db.com',
  'Capital One': 'capitalone.com',
  'US Bank': 'usbank.com',
  'PNC': 'pnc.com',
  'TD Bank': 'td.com',
  'Goldman Sachs': 'goldmansachs.com',
  'Morgan Stanley': 'morganstanley.com',
  'Charles Schwab': 'schwab.com',
  'Fidelity': 'fidelity.com',
  'Ally': 'ally.com',
  'Ally Bank': 'ally.com',
  'Discover': 'discover.com',
  'SoFi': 'sofi.com',
  'Varo': 'varomoney.com',
  'Chime': 'chime.com',
  'PayPal': 'paypal.com',
  'Venmo': 'venmo.com',
  'Cash App': 'cash.app',
  'Apple Cash': 'apple.com',
  'Google Pay': 'pay.google.com',
  'Western Union': 'westernunion.com',
  'MoneyGram': 'moneygram.com',
  'Remitly': 'remitly.com',
  'WorldRemit': 'worldremit.com',
  'XE': 'xe.com',
  'TransferWise': 'wise.com',
};

window.BANK_CATALOG = BANK_CATALOG;
