'use strict';
// Comprehensive bank catalog — PK / UK / UAE / US / intl.
// Single source of truth for domain → logo. Runtime uses local assets/banks/{slug}.png.

const BANK_CATALOG = {
  // ── Pakistan ──────────────────────────────────────────────
  'HBL': 'hbl.com',
  'Habib Bank': 'hbl.com',
  'HBL Bank': 'hbl.com',
  'UBL': 'ubl.com.pk',
  'United Bank': 'ubl.com.pk',
  'United Bank Limited': 'ubl.com.pk',
  'MCB': 'mcb.com.pk',
  'MCB Bank': 'mcb.com.pk',
  'ABL': 'abl.com',
  'Allied Bank': 'abl.com',
  'Allied': 'abl.com',
  'NBP': 'nbp.com.pk',
  'National Bank': 'nbp.com.pk',
  'National Bank of Pakistan': 'nbp.com.pk',
  'Meezan': 'meezanbank.com',
  'Meezan Bank': 'meezanbank.com',
  'Faysal': 'faysalbank.com',
  'Faysal Bank': 'faysalbank.com',
  'Askari': 'askaribank.com.pk',
  'Askari Bank': 'askaribank.com.pk',
  'Bank Alfalah': 'bankalfalah.com',
  'Alfalah': 'bankalfalah.com',
  'Bank Al Habib': 'bankalhabib.com',
  'BAHL': 'bankalhabib.com',
  'Habib Metro': 'habibmetro.com',
  'Habib Metro Bank': 'habibmetro.com',
  'Bank Islami': 'bankislami.com.pk',
  'Islami': 'bankislami.com.pk',
  'Silkbank': 'silkbank.com.pk',
  'Silk Bank': 'silkbank.com.pk',
  'Summit Bank': 'summitbank.com.pk',
  'Summit': 'summitbank.com.pk',
  'Soneri': 'soneribank.com',
  'Soneri Bank': 'soneribank.com',
  'JS Bank': 'jsbl.com',
  'JS': 'jsbl.com',
  'Bank of Punjab': 'bop.com.pk',
  'BOP': 'bop.com.pk',
  'Standard Chartered PK': 'sc.com',
  'Standard Chartered': 'sc.com',
  'Samba Bank': 'samba.com.pk',
  'Dubai Islamic Bank PK': 'dibpak.com',
  'Al Baraka': 'albaraka.com.pk',
  'Bank AlBaraka': 'albaraka.com.pk',
  'First Women Bank': 'fwbl.com.pk',
  'FWBL': 'fwbl.com.pk',
  'Sindh Bank': 'sindhbank.com.pk',
  'The Bank of Khyber': 'bok.com.pk',
  'BOK': 'bok.com.pk',
  'Industrial Development Bank': 'idbp.com.pk',
  'Zarai Taraqiati': 'ztbl.com.pk',
  'ZTBL': 'ztbl.com.pk',
  'Punjab Provincial Cooperative Bank': 'ppcb.com.pk',
  'Khushhali Microfinance': 'khushhalibank.com.pk',
  'Telenor Microfinance': 'telenorbank.pk',
  'U Microfinance': 'ubank.com.pk',
  'Mobilink Microfinance': 'jazzcash.com.pk',
  'Apna Microfinance': 'apnabank.com.pk',
  'NRSP Microfinance': 'nrspbank.com',
  'JazzCash': 'jazzcash.com.pk',
  'Jazz Cash': 'jazzcash.com.pk',
  'EasyPaisa': 'easypaisa.com.pk',
  'NayaPay': 'nayapay.com',
  'SadaPay': 'sadapay.com',
  'Sadapay': 'sadapay.com',
  'Zindigi': 'zindigi.com',
  'Bykea Pay': 'bykea.com',
  'Keepa': 'keepa.pk',

  // ── UK ────────────────────────────────────────────────────
  'Barclays': 'barclays.co.uk',
  'Barclaycard': 'barclays.co.uk',
  'Lloyds': 'lloydsbank.com',
  'Lloyds Bank': 'lloydsbank.com',
  'NatWest': 'natwest.com',
  'Nat West': 'natwest.com',
  'HSBC': 'hsbc.co.uk',
  'HSBC UK': 'hsbc.co.uk',
  'Santander': 'santander.co.uk',
  'Santander UK': 'santander.co.uk',
  'Nationwide': 'nationwide.co.uk',
  'Monzo': 'monzo.com',
  'Starling': 'starlingbank.com',
  'Starling Bank': 'starlingbank.com',
  'Revolut': 'revolut.com',
  'Wise': 'wise.com',
  'Monese': 'monese.com',
  'Halifax': 'halifax.co.uk',
  'First Direct': 'firstdirect.com',
  'Metro Bank': 'metrobankonline.co.uk',
  'Metro': 'metrobankonline.co.uk',
  'TSB': 'tsb.co.uk',
  'TSB Bank': 'tsb.co.uk',
  'Co-op': 'co-operativebank.co.uk',
  'Co-operative Bank': 'co-operativebank.co.uk',
  'Coop': 'co-operativebank.co.uk',
  'Virgin Money': 'virginmoney.com',
  'Virgin': 'virginmoney.com',
  'Chase UK': 'chase.co.uk',
  'Atom': 'atombank.co.uk',
  'Atom Bank': 'atombank.co.uk',
  'Al Rayan Bank': 'alrayanbank.co.uk',
  'Coutts': 'coutts.com',
  'Schroders Personal Wealth': 'schroderspersonalwealth.co.uk',
  'Investec': 'investec.com',
  'Shawbrook': 'shawbrook.co.uk',
  'Shawbrook Bank': 'shawbrook.co.uk',
  'Aldermore': 'aldermore.co.uk',
  'Tandem': 'tandem.co.uk',
  'Tandem Bank': 'tandem.co.uk',
  'Marcus': 'marcus.co.uk',
  'Marcus by Goldman Sachs': 'marcus.co.uk',
  'Smile': 'smile.co.uk',
  'Yorkshire Bank': 'ybonline.co.uk',
  'Clydesdale': 'cbonline.co.uk',
  'Bank of Scotland': 'bankofscotland.co.uk',
  'Royal Bank of Scotland': 'rbs.co.uk',
  'RBS': 'rbs.co.uk',
  'Ulster Bank': 'ulsterbank.co.uk',
  'Danske Bank UK': 'danskebank.co.uk',
  'Handelsbanken UK': 'handelsbanken.co.uk',
  'Tide': 'tide.co',
  'Anna Money': 'anna.money',
  'Cashplus': 'cashplus.com',
  'Curve': 'curve.com',
  'Chip': 'getchip.uk',
  'Plum': 'withplum.com',
  'Moneybox': 'moneyboxapp.com',
  'Trading 212': 'trading212.com',
  'Hargreaves Lansdown': 'hl.co.uk',
  'AJ Bell': 'ajbell.co.uk',
  'Interactive Investor': 'ii.co.uk',
  'Vanguard UK': 'vanguardinvestor.co.uk',

  // ── UAE ───────────────────────────────────────────────────
  'Emirates NBD': 'emiratesnbd.com',
  'ENBD': 'emiratesnbd.com',
  'Emirates': 'emiratesnbd.com',
  'FAB': 'bankfab.com',
  'First Abu Dhabi Bank': 'bankfab.com',
  'ADCB': 'adcb.com',
  'Abu Dhabi Commercial Bank': 'adcb.com',
  'RAKBank': 'rakbank.ae',
  'RAK Bank': 'rakbank.ae',
  'RAKBANK': 'rakbank.ae',
  'Mashreq': 'mashreq.com',
  'Mashreq Bank': 'mashreq.com',
  'DIB': 'dib.ae',
  'Dubai Islamic Bank': 'dib.ae',
  'ADIB': 'adib.ae',
  'Abu Dhabi Islamic Bank': 'adib.ae',
  'CBD': 'cbd.ae',
  'Commercial Bank of Dubai': 'cbd.ae',
  'Noor Bank': 'emiratesnbd.com',
  'Noor': 'emiratesnbd.com',
  'Wio': 'wio.io',
  'Wio Bank': 'wio.io',
  'Liv': 'liv.ae',
  'Liv.': 'liv.ae',
  'HSBC UAE': 'hsbc.ae',
  'Standard Chartered UAE': 'sc.com',
  'Citibank UAE': 'citibank.ae',
  'Ajman Bank': 'ajmanbank.ae',
  'United Arab Bank': 'uab.ae',
  'UAB': 'uab.ae',
  'National Bank of Fujairah': 'nbf.ae',
  'NBF': 'nbf.ae',
  'Bank of Sharjah': 'bankofsharjah.com',
  'Sharjah Islamic Bank': 'sib.ae',
  'SIB': 'sib.ae',
  'Al Hilal Bank': 'alhilalbank.ae',
  'Emirates Islamic': 'emiratesislamic.ae',
  'EI': 'emiratesislamic.ae',
  'Dubai Bank': 'dubaibank.ae',
  'Finance House': 'financehouse.ae',
  'Ruya': 'ruya.ae',

  // ── US / International ────────────────────────────────────
  'Chase': 'chase.com',
  'Chase Bank': 'chase.com',
  'Bank of America': 'bankofamerica.com',
  'BofA': 'bankofamerica.com',
  'Wells Fargo': 'wellsfargo.com',
  'Wells': 'wellsfargo.com',
  'Citi': 'citibank.com',
  'Citibank': 'citibank.com',
  'Citi Bank': 'citibank.com',
  'Amex': 'americanexpress.com',
  'American Express': 'americanexpress.com',
  'JPMorgan': 'jpmorgan.com',
  'JP Morgan': 'jpmorgan.com',
  'Deutsche Bank': 'db.com',
  'Deutsche': 'db.com',
  'Capital One': 'capitalone.com',
  'US Bank': 'usbank.com',
  'PNC': 'pnc.com',
  'TD Bank': 'td.com',
  'Goldman Sachs': 'goldmansachs.com',
  'Morgan Stanley': 'morganstanley.com',
  'Charles Schwab': 'schwab.com',
  'Fidelity': 'fidelity.com',
  'Ally': 'ally.com',
  'Ally Bank': 'ally.com',
  'Discover': 'discover.com',
  'SoFi': 'sofi.com',
  'Varo': 'varomoney.com',
  'Chime': 'chime.com',
  'PayPal': 'paypal.com',
  'Venmo': 'venmo.com',
  'Cash App': 'cash.app',
  'Apple Cash': 'apple.com',
  'Google Pay': 'pay.google.com',
  'Western Union': 'westernunion.com',
  'MoneyGram': 'moneygram.com',
  'Remitly': 'remitly.com',
  'WorldRemit': 'worldremit.com',
  'XE': 'xe.com',
  'TransferWise': 'wise.com',
  // ── SMART_DB coverage expansion (v5.1.8) ─────────────────
  'Pockit': 'pockit.com',
  'Deutsche Bank PK': 'db.com',
  'Deutsche Bank Pakistan': 'db.com',
  'Bank of China PK': 'boc.cn',
  'Bank of China Pakistan': 'boc.cn',
  'BOC Pakistan': 'boc.cn',
  'ICBC Pakistan': 'icbc.com.cn',
  'Industrial and Commercial Bank of China PK': 'icbc.com.cn',
  'ICBC PK': 'icbc.com.cn',
  'China Development Bank PK': 'cdb.com.cn',
  'CDB Pakistan': 'cdb.com.cn',
  'Bank of Azad Jammu and Kashmir': 'bajk.com.pk',
  'BAJK': 'bajk.com.pk',
  'Bank of AJK': 'bajk.com.pk',
  'AJK Bank': 'bajk.com.pk',
  'Al Baraka Bank PK': 'albaraka.com.pk',
  'Al Baraka Pakistan': 'albaraka.com.pk',
  'Albaraka Bank PK': 'albaraka.com.pk',
  'Al Baraka Bank (Pakistan)': 'albaraka.com.pk',
  'MCB Islamic Bank': 'mcbislamicbank.com',
  'MCB Islamic': 'mcbislamicbank.com',
  'MIB': 'mcbislamicbank.com',
  'UPaisa': 'upaisa.com',
  'U Paisa': 'upaisa.com',
  'Ufone Wallet': 'upaisa.com',
  'Ufone Mobile Paisa': 'upaisa.com',
  'TimePey': 'timepey.com',
  'Time Pey': 'timepey.com',
  'Finja': 'finja.pk',
  'SimSim': 'finja.pk',
  'Finja SimSim': 'finja.pk',
  'HBL Pay': 'hbl.com',
  'HBL Mobile Wallet': 'hbl.com',
  'HBL Konnect Digital': 'hbl.com',
  'MCB Lite': 'mcb.com.pk',
  'MCB Mobile': 'mcb.com.pk',
  'MCB Lite Prepaid': 'mcb.com.pk',
  'MCB Mobile App': 'mcb.com.pk',
  'PayFast': 'payfast.pk',
  'Pay Fast PK': 'payfast.pk',
  'TAG': 'tag.com.pk',
  'TAG Payment': 'tag.com.pk',
  'TAG Digital': 'tag.com.pk',
  'SME Bank': 'smebank.org',
  'SME Bank Pakistan': 'smebank.org',
  'Small and Medium Enterprise Bank': 'smebank.org',
  'HBFC': 'hbfc.com.pk',
  'House Building Finance Company': 'hbfc.com.pk',
  'House Building Finance Corporation': 'hbfc.com.pk',
  'Pakistan Post Savings': 'pakpost.gov.pk',
  'Pakistan Post Office Savings': 'pakpost.gov.pk',
  'PO Savings': 'pakpost.gov.pk',
  'Post Office Savings': 'pakpost.gov.pk',
  'HSBC Pakistan': 'hsbc.com.pk',
  'HSBC PK': 'hsbc.com.pk',
  'Citibank PK': 'citibank.com.pk',
  'Citi Pakistan': 'citibank.com.pk',
  'Citibank Pakistan': 'citibank.com.pk',
  'Citi PK': 'citibank.com.pk',
  'Citibank N.A. Pakistan': 'citibank.com.pk',
  'Khushhali Microfinance Bank': 'khushhalibank.com.pk',
  'Khushhali': 'khushhalibank.com.pk',
  'KMBL': 'khushhalibank.com.pk',
  'Khushhali Bank': 'khushhalibank.com.pk',
  'KMB': 'khushhalibank.com.pk',
  'Khushhali MFB': 'khushhalibank.com.pk',
  'NRSP Microfinance Bank': 'nrspbank.com',
  'NRSP': 'nrspbank.com',
  'NRSP Bank': 'nrspbank.com',
  'NRSP MFB': 'nrspbank.com',
  'NRSP Visa': 'nrspbank.com',
  'Apna Microfinance Bank': 'apnabank.com.pk',
  'Apna Bank': 'apnabank.com.pk',
  'Apna MFB': 'apnabank.com.pk',
  'Mobilink Microfinance Bank': 'jazzcash.com.pk',
  'MMBL': 'jazzcash.com.pk',
  'Mobilink Bank': 'jazzcash.com.pk',
  'Mobilink MFB': 'jazzcash.com.pk',
  'Telenor Microfinance Bank': 'telenorbank.pk',
  'TMB': 'telenorbank.pk',
  'Telenor MFB': 'telenorbank.pk',
  'U Microfinance Bank': 'ubank.com.pk',
  'U Bank': 'ubank.com.pk',
  'UMicro': 'ubank.com.pk',
  'U MFB': 'ubank.com.pk',
  'FINCA Microfinance Bank': 'finca.pk',
  'FINCA Pakistan': 'finca.pk',
  'FINCA MFB': 'finca.pk',
  'First MicroFinance Bank': 'fmfb.com.pk',
  'FMFB': 'fmfb.com.pk',
  'First Micro': 'fmfb.com.pk',
  'First MFB': 'fmfb.com.pk',
  'Kashf Microfinance Bank': 'kashf.org',
  'Kashf Bank': 'kashf.org',
  'Kashf MFB': 'kashf.org',
  'Kashf Foundation': 'kashf.org',
  'Akhuwat Islamic Microfinance': 'akhuwat.org.pk',
  'Akhuwat Bank': 'akhuwat.org.pk',
  'Akhuwat': 'akhuwat.org.pk',
  'HBL Microfinance Bank': 'hblmfb.com',
  'HBL MFB': 'hblmfb.com',
  'HBL Konnect MFB': 'hblmfb.com',
  'Sindh Microfinance Bank': 'sindhmfb.com',
  'Sindh MFB': 'sindhmfb.com',
  'Advans Pakistan Microfinance Bank': 'advanspakistan.com',
  'Advans MFB': 'advanspakistan.com',
  'Advans Pakistan': 'advanspakistan.com',
  'ASA Microfinance Bank': 'asapower.org',
  'ASA Pakistan': 'asapower.org',
  'ASA MFB': 'asapower.org',
  'Pak Oman Microfinance Bank': 'pomicro.com',
  'Pak Oman MFB': 'pomicro.com',
  'Pak Oman Investment Company': 'pakoman.com',
  'Pak Oman': 'pakoman.com',
  'POIC': 'pakoman.com',
  'Pak Kuwait Investment Company': 'pkic.com',
  'Pak Kuwait': 'pkic.com',
  'PKIC': 'pkic.com',
  'Pak Brunei Investment Company': 'pakbrunei.com.pk',
  'Pak Brunei': 'pakbrunei.com.pk',
  'PBIC': 'pakbrunei.com.pk',
  'Pak China Investment Company': 'pcic.com.pk',
  'Pak China': 'pcic.com.pk',
  'PCIC': 'pcic.com.pk',
  'Saudi Pak Industrial and Agricultural Investment': 'saudipak.com',
  'Saudi Pak': 'saudipak.com',
  'SAPICO': 'saudipak.com',
  'PAIR Investment Company': 'pair.com.pk',
  'PAIR': 'pair.com.pk',
  'Pak Libya Holding Company': 'paklibya.com.pk',
  'Pak Libya': 'paklibya.com.pk',
  'Pakistan Kuwait Investment': 'pkic.com',
  'PKI': 'pkic.com',
  'Post Office Money': 'postoffice.co.uk',
  'Post Office Bank': 'postoffice.co.uk',
  'PO Money': 'postoffice.co.uk',
  'Close Brothers': 'closebrothers.com',
  'Close Brothers Bank': 'closebrothers.com',
  'Paragon Bank': 'paragonbank.co.uk',
  'Paragon': 'paragonbank.co.uk',
  'Secure Trust Bank': 'securetrustbank.com',
  'Secure Trust': 'securetrustbank.com',
  'OneSavings Bank': 'onesavingsbank.com',
  'OSB': 'onesavingsbank.com',
  'OSB Group': 'onesavingsbank.com',
  'Charter Savings Bank': 'onesavingsbank.com',
  'Cynergy Bank': 'cynergybank.co.uk',
  'Cynergy': 'cynergybank.co.uk',
  'Bank of Cyprus UK': 'cynergybank.co.uk',
  'Hampden & Co': 'hampden.co.uk',
  'Hampden Bank': 'hampden.co.uk',
  'Brown Shipley': 'brownshipley.com',
  'Brown Shipley Bank': 'brownshipley.com',
  'Arbuthnot Latham': 'arbuthnotlatham.co.uk',
  'Arbuthnot': 'arbuthnotlatham.co.uk',
  'Weatherbys Bank': 'weatherbys.bank',
  'Weatherbys': 'weatherbys.bank',
  'C. Hoare & Co': 'hoaresbank.co.uk',
  'Hoare Bank': 'hoaresbank.co.uk',
  'C Hoare': 'hoaresbank.co.uk',
  'Duncan Lawrie': 'duncanlawrie.com',
  'Duncan Lawrie Bank': 'duncanlawrie.com',
  'Skipton Building Society': 'skipton.co.uk',
  'Skipton': 'skipton.co.uk',
  'Yorkshire Building Society': 'ybs.co.uk',
  'YBS': 'ybs.co.uk',
  'Yorkshire BS': 'ybs.co.uk',
  'Coventry Building Society': 'coventrybuildingsociety.co.uk',
  'Coventry BS': 'coventrybuildingsociety.co.uk',
  'Coventry': 'coventrybuildingsociety.co.uk',
  'Leeds Building Society': 'leedsbuildingsociety.co.uk',
  'Leeds BS': 'leedsbuildingsociety.co.uk',
  'Principality Building Society': 'principality.co.uk',
  'Principality': 'principality.co.uk',
  'Newcastle Building Society': 'newcastle.co.uk',
  'Newcastle BS': 'newcastle.co.uk',
  'Nottingham Building Society': 'thenottingham.com',
  'Nottingham BS': 'thenottingham.com',
  'West Bromwich Building Society': 'westbrom.co.uk',
  'West Brom': 'westbrom.co.uk',
  'West Bromwich BS': 'westbrom.co.uk',
  'Cambridge Building Society': 'cambridgebs.co.uk',
  'Cambridge BS': 'cambridgebs.co.uk',
  'Cumberland Building Society': 'cumberland.co.uk',
  'Cumberland BS': 'cumberland.co.uk',
  'Furness Building Society': 'furnessbs.co.uk',
  'Furness BS': 'furnessbs.co.uk',
  'Progressive Building Society': 'theprogressive.com',
  'Progressive BS': 'theprogressive.com',
  'Saffron Building Society': 'saffronbs.co.uk',
  'Saffron BS': 'saffronbs.co.uk',
  'Teachers Building Society': 'teachersbs.co.uk',
  'Teachers BS': 'teachersbs.co.uk',
  'Ecology Building Society': 'ecology.co.uk',
  'Ecology BS': 'ecology.co.uk',
  'Suits Me': 'suitsme.card',
  'SuitsMe': 'suitsme.card',
  'Allica Bank': 'allica.bank',
  'Allica': 'allica.bank',
  'OakNorth Bank': 'oaknorth.co.uk',
  'OakNorth': 'oaknorth.co.uk',
  'Monument Bank': 'monument.co',
  'Monument': 'monument.co',
  'Zopa Bank': 'zopa.com',
  'Zopa': 'zopa.com',
  'Paysend': 'paysend.com',
  'Dozens': 'paysend.com',
  'Paysend UK': 'paysend.com',
  'Zabel': 'zabel.io',
  'Zable': 'zabel.io',
  'Zabel Visa': 'zabel.io',
  'Yonder': 'yonder.co.uk',
  'Yonder Credit': 'yonder.co.uk',
  'Wirex': 'wirexapp.com',
  'Wirex Visa': 'wirexapp.com',
  'Wirex Bank': 'wirexapp.com',
  'Klarna': 'klarna.com',
  'Klarna Card': 'klarna.com',
  'Klarna Bank': 'klarna.com',
  'Freetrade': 'freetrade.io',
  'Freetrade Cash': 'freetrade.io',
  'Nutmeg': 'nutmeg.com',
  'Nutmeg Invest': 'nutmeg.com',
  'Raisin UK': 'raisin.co.uk',
  'Raisin': 'raisin.co.uk',
  'Flagstone': 'flagstoneim.com',
  'Flagstone Cash': 'flagstoneim.com',
  'Gatehouse Bank': 'gatehousebank.com',
  'Gatehouse': 'gatehousebank.com',
  'Ansar Finance': 'ansarfinance.com',
  'Ansar Housing': 'ansarfinance.com',
  'BLME': 'blme.com',
  'Bank of London and The Middle East': 'blme.com',
  'Citibank UK': 'citibank.co.uk',
  'Citi UK': 'citibank.co.uk',
  'JP Morgan UK': 'jpmorgan.com',
  'JPMorgan UK': 'jpmorgan.com',
  'J.P. Morgan UK': 'jpmorgan.com',
  'Bank of China UK': 'bankofchina.com',
  'BOC UK': 'bankofchina.com',
  'ICBC UK': 'icbc.com.cn',
  'ICBC London': 'icbc.com.cn',
  'State Bank of India UK': 'sbiuk.com',
  'SBI UK': 'sbiuk.com',
  'Habib Bank AG Zurich UK': 'habibbank.com',
  'Habib Bank Zurich UK': 'habibbank.com',
  'United National Bank UK': 'ubluk.com',
  'UNB UK': 'ubluk.com',
  'United Bank UK': 'ubluk.com',
  'Investbank': 'investbank.ae',
  'Invest Bank UAE': 'investbank.ae',
  'National Bank of Umm Al Qaiwain': 'nbq.ae',
  'NBQ': 'nbq.ae',
  'NBQ UAE': 'nbq.ae',
  'Arab Bank UAE': 'arabbank.ae',
  'Arab Bank Dubai': 'arabbank.ae',
  'Commercial Bank International': 'cbiuae.com',
  'CBI UAE': 'cbiuae.com',
  'CBI': 'cbiuae.com',
  'Emirates Investment Bank': 'eib.ae',
  'EIB Investment': 'eib.ae',
  'Al Maryah Community Bank': 'almaryahbank.com',
  'Al Maryah': 'almaryahbank.com',
  'Maryah Bank': 'almaryahbank.com',
  'Aafaq Islamic Finance': 'aafaq.ae',
  'Aafaq': 'aafaq.ae',
  'Alinma Abu Dhabi': 'alinma.com',
  'Alinma Bank UAE': 'alinma.com',
  'YAP': 'yap.ae',
  'YAP UAE': 'yap.ae',
  'NOW Money': 'nowmoney.me',
  'Now Money UAE': 'nowmoney.me',
  'Zand Bank': 'zand.ae',
  'Zand': 'zand.ae',
  'Nomo Bank': 'nomobank.com',
  'Nomo': 'nomobank.com',
  'CD Bank': 'cdb.ae',
  'CD Bank UAE': 'cdb.ae',
  'Barclays UAE': 'barclays.ae',
  'Barclays Dubai': 'barclays.ae',
  'Bank of Baroda UAE': 'bankofbaroda.ae',
  'BOB UAE': 'bankofbaroda.ae',
  'Banque Misr UAE': 'banquemisr.ae',
  'Banque Misr Dubai': 'banquemisr.ae',
  'BNP Paribas UAE': 'bnpparibas.ae',
  'BNP UAE': 'bnpparibas.ae',
  'Habib Bank AG Zurich UAE': 'habibbank.com',
  'Habib Bank Zurich UAE': 'habibbank.com',
  'ICBC UAE': 'icbc.ae',
  'ICBC Dubai': 'icbc.ae',
  'United Bank Ltd UAE': 'ubl.com.pk',
  'UBL UAE': 'ubl.com.pk',
  'United Bank UAE': 'ubl.com.pk',
  'National Bank of Bahrain UAE': 'nbbonline.com',
  'NBB UAE': 'nbbonline.com',
  'National Bank of Oman UAE': 'nbo.om',
  'NBO UAE': 'nbo.om',
  'Arab Banking Corporation UAE': 'bank-abc.com',
  'Bank ABC UAE': 'bank-abc.com',
  'ABC UAE': 'bank-abc.com',
  'American Express UK': 'americanexpress.com',
  'Amex UK': 'americanexpress.com',
  'AMEX UK': 'americanexpress.com',
  'American Express UAE': 'americanexpress.com',
  'Amex UAE': 'americanexpress.com',
  'AMEX UAE': 'americanexpress.com',
  'Tesco Bank': 'tescobank.com',
  'Tesco': 'tescobank.com',
  'Sainsbury\'s Bank': 'sainsburysbank.co.uk',
  'Sainsburys Bank': 'sainsburysbank.co.uk',
  'Sainsbury Bank': 'sainsburysbank.co.uk',
  'M&S Bank': 'marksandspencer.com',
  'Marks and Spencer Bank': 'marksandspencer.com',
  'Marks & Spencer Bank': 'marksandspencer.com',
  'M and S Bank': 'marksandspencer.com',
  'Asda Money': 'money.asda.com',
  'Asda': 'money.asda.com',
  'ASDA Money': 'money.asda.com',
  'Capital One UK': 'capitalone.co.uk',
  'Capital One UK Bank': 'capitalone.co.uk',
  'Aqua': 'aquacard.co.uk',
  'Aqua Card': 'aquacard.co.uk',
  'Aqua Credit': 'aquacard.co.uk',
  'Vanquis': 'vanquis.co.uk',
  'Vanquis Bank': 'vanquis.co.uk',
  'Caxton': 'caxtonfx.com',
  'Caxton FX': 'caxtonfx.com',
  'Caxton Card': 'caxtonfx.com',
  'FairFX': 'fairfx.com',
  'Equals Money': 'fairfx.com',
  'Fair FX': 'fairfx.com',
  'John Lewis': 'johnlewis.com',
  'John Lewis Partnership': 'johnlewis.com',
  'John Lewis Finance': 'johnlewis.com',
  'Marbles': 'marbles.com',
  'Marbles Card': 'marbles.com',
  'AA Finance': 'theaa.com',
  'AA Credit Card': 'theaa.com',
  'AA Card': 'theaa.com',
  'RAC Finance': 'rac.co.uk',
  'RAC Credit Card': 'rac.co.uk',
  'RAC Card': 'rac.co.uk',
  'Apple Card': 'apple.com',
  'Apple Card Goldman': 'apple.com',
  'Goldman Sachs Apple': 'apple.com',
  'Citi US': 'citi.com',
  'Citi Bank US': 'citi.com',
  'Citibank US': 'citi.com',
  'Al Rajhi Bank': 'alrajhibank.com.sa',
  'Al Rajhi': 'alrajhibank.com.sa',
  'Rajhi Bank': 'alrajhibank.com.sa',
  'AlRajhi': 'alrajhibank.com.sa',
  'SNB': 'alahli.com',
  'Saudi National Bank': 'alahli.com',
  'AlAhli': 'alahli.com',
  'Al Ahli Bank': 'alahli.com',
  'NCB Saudi': 'alahli.com',
  'Riyad Bank': 'riyadbank.com',
  'Riyadh Bank': 'riyadbank.com',
  'Alinma Bank': 'alinma.com',
  'Alinma': 'alinma.com',
  'Banque Saudi Fransi': 'alfransi.com.sa',
  'BSF': 'alfransi.com.sa',
  'Saudi Fransi': 'alfransi.com.sa',
  'ANB': 'anb.com.sa',
  'Arab National Bank': 'anb.com.sa',
  'Arab National Bank Saudi': 'anb.com.sa',
  'SABB': 'sabb.com',
  'Saudi British Bank': 'sabb.com',
  'SAB': 'sabb.com',
  'Bank AlJazira': 'baj.com.sa',
  'AlJazira': 'baj.com.sa',
  'Al Jazira Bank': 'baj.com.sa',
  'Bank Albilad': 'bankalbilad.com',
  'Albilad': 'bankalbilad.com',
  'Al Bilad': 'bankalbilad.com',
  'HDFC Bank': 'hdfcbank.com',
  'HDFC': 'hdfcbank.com',
  'ICICI Bank': 'icicibank.com',
  'ICICI': 'icicibank.com',
  'SBI': 'sbi.co.in',
  'State Bank of India': 'sbi.co.in',
  'State Bank': 'sbi.co.in',
  'Axis Bank': 'axisbank.com',
  'Axis': 'axisbank.com',
  'Kotak Mahindra Bank': 'kotak.com',
  'Kotak': 'kotak.com',
  'Kotak Bank': 'kotak.com',
  'Yes Bank': 'yesbank.in',
  'YES Bank': 'yesbank.in',
  'IndusInd Bank': 'indusind.com',
  'IndusInd': 'indusind.com',
  'IDFC First Bank': 'idfcfirstbank.com',
  'IDFC': 'idfcfirstbank.com',
  'IDFC First': 'idfcfirstbank.com',
  'QNB': 'qnb.com',
  'Qatar National Bank': 'qnb.com',
  'QNB Qatar': 'qnb.com',
  'Commercial Bank Qatar': 'cbq.qa',
  'CBQ': 'cbq.qa',
  'Commercial Bank of Qatar': 'cbq.qa',
  'Doha Bank': 'dohabank.com',
  'Doha Bank Qatar': 'dohabank.com',
  'QIB': 'qib.com.qa',
  'Qatar Islamic Bank': 'qib.com.qa',
  'Masraf Al Rayan': 'alrayan.com',
  'Al Rayan Qatar': 'alrayan.com',
  'MAR': 'alrayan.com',
  'NBK': 'nbk.com',
  'National Bank of Kuwait': 'nbk.com',
  'KFH': 'kfh.com',
  'Kuwait Finance House': 'kfh.com',
  'Gulf Bank': 'gulfbank.com',
  'Gulf Bank Kuwait': 'gulfbank.com',
  'Boubyan Bank': 'bankboubyan.com',
  'Boubyan': 'bankboubyan.com',
  'Burgan Bank': 'burgan.com',
  'Burgan': 'burgan.com',
  'NBB': 'nbbonline.com',
  'National Bank of Bahrain': 'nbbonline.com',
  'Ahli United Bank': 'ahliunited.com',
  'AUB': 'ahliunited.com',
  'Ahli United': 'ahliunited.com',
  'Bank of Bahrain and Kuwait': 'bbkonline.com',
  'BBK': 'bbkonline.com',
  'Al Baraka Bank Bahrain': 'albaraka.bh',
  'Al Baraka Bahrain': 'albaraka.bh',
  'Bank Muscat': 'bankmuscat.com',
  'Muscat Bank': 'bankmuscat.com',
  'NBO': 'nbo.om',
  'National Bank of Oman': 'nbo.om',
  'Bank Dhofar': 'bankdhofar.com',
  'Dhofar Bank': 'bankdhofar.com',
  'Sohar International': 'soharinternational.com',
  'Sohar Bank': 'soharinternational.com',
  'Bank Sohar': 'soharinternational.com',
  'RBC': 'rbc.com',
  'Royal Bank of Canada': 'rbc.com',
  'RBC Royal Bank': 'rbc.com',
  'TD Canada Trust': 'td.com',
  'TD': 'td.com',
  'TD Canada': 'td.com',
  'TD CT': 'td.com',
  'Toronto Dominion Canada': 'td.com',
  'TD Cash Back': 'td.com',
  'Scotiabank': 'scotiabank.com',
  'Bank of Nova Scotia': 'scotiabank.com',
  'Scotia': 'scotiabank.com',
  'BMO': 'bmo.com',
  'Bank of Montreal': 'bmo.com',
  'BMO Bank': 'bmo.com',
  'CIBC': 'cibc.com',
  'Canadian Imperial Bank of Commerce': 'cibc.com',
  'National Bank of Canada': 'nbc.ca',
  'NBC': 'nbc.ca',
  'Banque Nationale': 'nbc.ca',
  'Tangerine': 'tangerine.ca',
  'Tangerine Bank': 'tangerine.ca',
  'Simplii Financial': 'simplii.com',
  'Simplii': 'simplii.com',
  'Commonwealth Bank': 'commbank.com.au',
  'CBA': 'commbank.com.au',
  'CommBank': 'commbank.com.au',
  'Westpac': 'westpac.com.au',
  'Westpac Banking': 'westpac.com.au',
  'WBC': 'westpac.com.au',
  'ANZ': 'anz.com',
  'ANZ Bank': 'anz.com',
  'Australia and New Zealand Banking': 'anz.com',
  'NAB': 'nab.com.au',
  'National Australia Bank': 'nab.com.au',
  'Macquarie Bank': 'macquarie.com',
  'Macquarie': 'macquarie.com',
  'ING Australia': 'ing.com.au',
  'ING AU': 'ing.com.au',
  'ING Direct Australia': 'ing.com.au',
  'UBank': 'ubank.com.au',
  'UBank Australia': 'ubank.com.au',
  'DBS': 'dbs.com',
  'DBS Bank': 'dbs.com',
  'Development Bank of Singapore': 'dbs.com',
  'OCBC': 'ocbc.com',
  'OCBC Bank': 'ocbc.com',
  'Oversea-Chinese Banking': 'ocbc.com',
  'UOB': 'uob.com.sg',
  'United Overseas Bank': 'uob.com.sg',
  'HSBC Singapore': 'hsbc.com.sg',
  'HSBC SG': 'hsbc.com.sg',
  'HSBC Hong Kong': 'hsbc.com.hk',
  'HSBC HK': 'hsbc.com.hk',
  'Hang Seng Bank': 'hangseng.com',
  'Hang Seng': 'hangseng.com',
  'Bank of China HK': 'bochk.com',
  'BOC Hong Kong': 'bochk.com',
  'BOCHK': 'bochk.com',
  'Commerzbank': 'commerzbank.com',
  'Commerz': 'commerzbank.com',
  'N26': 'n26.com',
  'N26 Bank': 'n26.com',
  'BNP Paribas': 'bnpparibas.com',
  'BNP': 'bnpparibas.com',
  'Societe Generale': 'societegenerale.com',
  'SocGen': 'societegenerale.com',
  'Société Générale': 'societegenerale.com',
  'Credit Agricole': 'credit-agricole.com',
  'Crédit Agricole': 'credit-agricole.com',
  'CA Bank': 'credit-agricole.com',
  'ING Netherlands': 'ing.nl',
  'ING NL': 'ing.nl',
  'ING Bank NL': 'ing.nl',
  'Bunq': 'bunq.com',
  'bunq': 'bunq.com',
  'ING Germany': 'ing.de',
  'ING DE': 'ing.de',
  'ING-DiBa': 'ing.de',
};

window.BANK_CATALOG = BANK_CATALOG;
