function renderAlerts(){
  const b=document.getElementById('alertBody');if(!b)return;
  if(!window._vosUnlocked){b.innerHTML='<div style="text-align:center;padding:60px 20px;color:var(--text3)">Unlock vault to see alerts</div>';return;}
  const st=(ic,t)=>`<span class="chip-ic">${VC.icon(ic,14)}</span>${t}`;
  const expCards=S.cards.filter(c=>{const s=U.expSt(c.expiry);return s!=='ok';});
  const expDocs=(S.documents||[]).filter(d=>{const exp=typeof docExpiry==='function'?docExpiry(d):(d.expiryDate||d.expiry);if(!exp)return false;const dt=new Date(exp);if(isNaN(dt))return false;return dt<new Date(Date.now()+60*864e5);});
  const simR=S.sims.filter(s=>s.rechargeReminder&&s.nextRecharge);
  const insR=S.assets.filter(a=>a.assetType==='insurance'&&a.renewalDate);
  const subR=S.expenses.filter(e=>e.renewalDate&&e.active);
  const mortgProp=S.assets.filter(a=>a.assetType==='property'&&a.mortgType&&a.mortgType!=='None'&&a.mortgBalance>0);
  const warnGadgets=S.gadgets.filter(g=>g.warranty&&new Date(g.warranty)<new Date(Date.now()+30*864e5));
  const loansDueAsset=S.assets.filter(a=>a.assetType==='loan'&&a.dueDate&&new Date(a.dueDate)<new Date(Date.now()+7*864e5));
  const loansDueMod=(S.loans||[]).filter(l=>l.dueDate&&l.status!=='Settled'&&new Date(l.dueDate)<new Date(Date.now()+7*864e5));
  const loansDue=[...loansDueAsset,...loansDueMod];
  const noSec=S.emails.filter(e=>!e.mfaEnabled);
  const noAlerts=[expCards,expDocs,simR,insR,subR,warnGadgets,loansDue].every(a=>!a.length);
  b.innerHTML=`
  ${expCards.length?`<div class="set-sec"><div class="set-title">${st('card','Card Expiry')}</div><div class="set-card">${expCards.map(c=>`<div class="si"><div class="sil"><div class="name">${escHtml(c.cardName)}</div><div class="desc">Expires ${escHtml(c.expiry)}</div></div>${U.expBadge(c.expiry)}<button type="button" class="btn btn-g btn-sm" onclick="Cards.edit('${c.id}')">Update</button></div>`).join('')}</div></div>`:''}
  ${expDocs.length?`<div class="set-sec"><div class="set-title">${st('id-card','Document Expiry')}</div><div class="set-card">${expDocs.map(d=>{const exp=docExpiry(d);const label=(typeof DOC_SCHEMAS!=='undefined'&&DOC_SCHEMAS[d.docType])?DOC_SCHEMAS[d.docType].label:d.docType||'Document';return `<div class="si"><div class="sil"><div class="name">${escHtml(d.holderName||label)}</div><div class="desc">Expires ${escHtml(exp)}</div></div><button type="button" class="btn btn-g btn-sm" onclick="DocsModule.edit('${d.id}')">Update</button></div>`;}).join('')}</div></div>`:''}
  ${simR.length?`<div class="set-sec"><div class="set-title">${st('smartphone','SIM Recharge')}</div><div class="set-card">${simR.map(s=>`<div class="si"><div class="sil"><div class="name">${escHtml(s.network)} (${U.flag(s.country)})</div><div class="desc">Recharge by ${escHtml(s.nextRecharge)}</div></div><button type="button" class="btn btn-g btn-sm" onclick="Sims.edit('${s.id}')">Update</button></div>`).join('')}</div></div>`:''}
  ${insR.length?`<div class="set-sec"><div class="set-title">${st('shield','Insurance Renewals')}</div><div class="set-card">${insR.map(a=>`<div class="si"><div class="sil"><div class="name">${escHtml(a.name)}</div><div class="desc">${escHtml(a.insuranceType||'')} · Renews ${escHtml(a.renewalDate)}</div></div><button type="button" class="btn btn-g btn-sm" onclick="Assets.edit('${a.id}')">Update</button></div>`).join('')}</div></div>`:''}
  ${subR.length?`<div class="set-sec"><div class="set-title">${st('repeat','Subscription Renewals')}</div><div class="set-card">${subR.map(e=>`<div class="si"><div class="sil"><div class="name"><span class="chip-ic">${VC.expenseIcon(e.icon,12)}</span>${escHtml(e.name)}</div><div class="desc">Renews ${escHtml(e.renewalDate)} · ${escHtml(e.currency||'')} ${U.fmt(e.amount)}/mo</div></div><button type="button" class="btn btn-g btn-sm" onclick="Exp.edit('${e.id}')">Update</button></div>`).join('')}</div></div>`:''}
  ${warnGadgets.length?`<div class="set-sec"><div class="set-title">${st('laptop','Warranty Expiring (30 days)')}</div><div class="set-card">${warnGadgets.map(g=>`<div class="si"><div class="sil"><div class="name"><span class="chip-ic">${VC.iconKey(g.ic||'laptop',12)}</span>${escHtml(g.name)}</div><div class="desc">Warranty expires ${new Date(g.warranty).toLocaleDateString('en-GB')}</div></div><button type="button" class="btn btn-g btn-sm" onclick="Gadgets.edit('${g.id}')">Update</button></div>`).join('')}</div></div>`:''}
  ${loansDue.length?`<div class="set-sec"><div class="set-title">${st('banknote','Loans Due Soon')}</div><div class="set-card">${loansDue.map(a=>{const isMod=a.person!=null;const name=isMod?(a.person||'Loan'):(a.name||'Loan');const amt=isMod?(a.amount||0):(a.loanBalance||0);const cur=a.currency||'';const due=a.dueDate||'';const edit=isMod?`Loans.edit('${a.id}')`:`Assets.edit('${a.id}')`;return `<div class="si"><div class="sil"><div class="name">${escHtml(name)}</div><div class="desc">Due ${escHtml(due)} · ${escHtml(cur)} ${U.fmt(amt)} outstanding</div></div><button type="button" class="btn btn-g btn-sm" onclick="${edit}">Update</button></div>`;}).join('')}</div></div>`:''}
  ${mortgProp.length?`<div class="set-sec"><div class="set-title">${st('bank','Mortgage Overview')}</div><div class="set-card">${mortgProp.map(a=>`<div class="si"><div class="sil"><div class="name">${escHtml(a.name)}</div><div class="desc">${escHtml(a.mortgLender||'')} · ${escHtml(a.currency||'')} ${U.fmt(a.mortgBalance)} outstanding · ${a.mortgRate||0}% rate</div></div><span class="badge b-warn">${escHtml(a.currency||'')} ${U.fmt(a.mortgPayment||0)}/mo</span></div>`).join('')}</div></div>`:''}
  ${noSec.length?`<div class="set-sec"><div class="set-title">${st('lock','Security — Emails Without 2FA')}</div><div class="set-card">${noSec.map(e=>`<div class="si"><div class="sil"><div class="name">${escHtml(e.email)}</div><div class="desc">${escHtml(e.purpose||'')} — No 2FA enabled</div></div><button type="button" class="btn btn-g btn-sm" onclick="Emails.edit('${e.id}')">Fix</button></div>`).join('')}</div></div>`:''}
  ${noAlerts&&!noSec.length?`<div class="empty"><div class="ei-ic">${VC.icon('target',32)}</div><h3>All clear!</h3><p>No alerts right now. Keep your details updated to stay on top of renewals and reminders.</p></div>`:''}`;
}
