const Digital={
  render(){
    const q=(document.getElementById('digQ')?.value||'').toLowerCase();
    const data=S.digital.filter(d=>!q||JSON.stringify(d).toLowerCase().includes(q));
    const el=document.getElementById('digItems');if(!el)return;
    if(!data.length){el.innerHTML=`<div class="empty-ios"><div class="ei-ic">💼</div><div class="ei-title">No Digital Accounts</div><div class="ei-sub">Store logins, wallets, social media and services — encrypted locally</div><button type="button" class="btn btn-p" onclick="Digital.openAdd()">💼 Add Account</button></div>`;return;}
    const byCat={};data.forEach(d=>{(byCat[d.category||'Other']=byCat[d.category||'Other']||[]).push(d);});
    el.innerHTML=Object.entries(byCat).map(([cat,items])=>`<div class="sdiv">${escHtml(cat)} (${items.length})</div>${items.map(d=>`<div class="entry"><div class="entry-main"><div class="entry-ic">${VC.icon('key', 18)}</div><div class="entry-body"><div class="entry-name">${escHtml(d.serviceName)}</div><div class="entry-sub">${d.username?'@'+escHtml(d.username):''} ${d.email?'· '+escHtml(d.email):''} ${d.url?'· '+escHtml(d.url.replace('https://','').replace('http://','').split('/')[0]):''}</div><div class="entry-meta">${d.twoFAEnabled?'<span class="badge b-ok">2FA ✓</span>':'<span class="badge b-err">No 2FA</span>'} ${d.balance?`<span class="badge b-acc">${escHtml(d.currency||'')} ${escHtml(d.balance)}</span>`:''} ${d.verificationStatus?`<span class="badge b-muted">${escHtml(d.verificationStatus)}</span>`:''} ${d.plan?`<span class="badge b-muted">${escHtml(d.plan)}</span>`:''}</div></div><div class="entry-acts">${U.actsViewEditDel('Digital', d.id)}</div></div></div>`).join('')}`).join('');
  },
  openAdd(){Modal.open('Add Digital Account',this.form(),`<button type="button" class="btn btn-g" onclick="Modal.close()">Cancel</button><button type="button" class="btn btn-p" onclick="Digital.save()">Save</button>`);},
  form(d={}){
    const emailOpts=S.emails.map(e=>`<option value="${escAttr(e.email)}"${d.email===e.email?' selected':''}>${e.email} (${e.purpose||''})</option>`).join('');
    return `<datalist id="digDL">${COMMON_SERVICES.map(s=>`<option value="${escAttr(s)}">`).join('')}</datalist>
    <div class="fg"><label class="fl">Service / Website *</label><input class="inp" id="df-name" value="${escAttr(d.serviceName||'')}" list="digDL" placeholder="Instagram, ChatGPT, PayPal, GitHub..." autocomplete="off"></div>
    <div class="fr"><div class="fg"><label class="fl">Category</label><datalist id="dfCatDL">${DIGITAL_CATS.map(c=>`<option value="${escAttr(c)}">`).join('')}</datalist><input class="inp" id="df-cat" value="${escAttr(d.category||'')}" list="dfCatDL" placeholder="Social Media, AI Tools..."></div><div class="fg"><label class="fl">Website URL</label><input class="inp" id="df-url" value="${escAttr(d.url||'')}" placeholder="https://..."></div></div>
    <div class="fr"><div class="fg"><label class="fl">Username / Handle</label><input class="inp" id="df-user" value="${escAttr(d.username||'')}" placeholder="@username or user ID"></div><div class="fg"><label class="fl">Linked Email</label><select class="inp" id="df-email"><option value="">— Select or type below —</option>${emailOpts}<option value="custom">+ Custom email</option></select></div></div>
    <div class="fg" id="df-customWrap" style="${!S.emails.find(e=>e.email===d.email)&&d.email?'':'display:none'}"><label class="fl">Email (if not listed above)</label><input class="inp" id="df-cemail" value="${escAttr(!S.emails.find(e=>e.email===d.email)?d.email||'':'')}" type="email" placeholder="email@..."></div>
    <div class="fg"><label class="fl">Password Hint — NEVER store actual passwords</label><input class="inp" id="df-pwd" value="${escAttr(d.pwdHint||'')}" placeholder="e.g. 'Usual pattern + !23' or 'Stored in 1Password'"></div>
    <div class="fr"><div class="fg"><label class="fl">2FA Method</label><datalist id="df2faDL"><option>None</option><option>SMS</option><option>Authenticator App</option><option>Email</option><option>Hardware Key</option><option>Passkey</option></datalist><input class="inp" id="df-2fa" value="${escAttr(d.twoFA||'None')}" list="df2faDL" placeholder="None, SMS, Authenticator..."></div><div class="fg"><label class="fl">Verification Status</label><datalist id="dfVDL"><option>Verified</option><option>Unverified</option><option>KYC Pending</option><option>KYC Complete</option></datalist><input class="inp" id="df-vstatus" value="${escAttr(d.verificationStatus||'')}" list="dfVDL" placeholder="Verified, KYC..."></div></div>
    <div class="fr"><div class="fg"><label class="fl">Balance / Credits</label><input class="inp" id="df-bal" value="${escAttr(d.balance||'')}" placeholder="0.00"></div><div class="fg"><label class="fl">Currency</label><select class="inp" id="df-cur">${U.currencies()}</select></div></div>
    <div class="fr"><div class="fg"><label class="fl">Account Tier / Plan</label><datalist id="dfPlanDL"><option>Free</option><option>Premium</option><option>Pro</option><option>Plus</option><option>Business</option><option>Enterprise</option></datalist><input class="inp" id="df-plan" value="${escAttr(d.plan||'')}" list="dfPlanDL" placeholder="Free, Premium, Pro..."></div><div class="fg"><label class="fl">Linked Phone</label><input class="inp" id="df-phone" value="${escAttr(d.phone||S.user.phone||'')}" placeholder="+44..."></div></div>
    <div class="fg"><label class="fl">Notes</label><textarea class="inp" id="df-notes" rows="2">${escAttr(d.notes||'')}</textarea></div>
    <div class="fg"><label class="fl">Tags</label>${U.tags(d.tags||[])}</div>
    <label style="display:flex;align-items:center;gap:8px;cursor:pointer;font-size:13px;margin-top:4px"><input type="checkbox" id="df-2fab" ${d.twoFAEnabled?'checked':''}> 🔒 2FA / MFA Enabled</label>`;
  },
  save(editId=null){
    const name=document.getElementById('df-name').value.trim();if(!name){Toast.show('Service name required','warning');return;}
    const emailSel=document.getElementById('df-email').value;
    const email=emailSel==='custom'?document.getElementById('df-cemail')?.value.trim():emailSel;
    const g=id=>{const e=document.getElementById(id);return e?e.value:''};
    const item={id:editId||U.id(),serviceName:name,category:g('df-cat'),url:g('df-url'),username:g('df-user'),email,pwdHint:g('df-pwd'),twoFA:g('df-2fa'),verificationStatus:g('df-vstatus'),balance:g('df-bal'),currency:g('df-cur'),plan:g('df-plan'),phone:g('df-phone'),notes:g('df-notes'),tags:U.getTags(),twoFAEnabled:document.getElementById('df-2fab').checked,createdAt:editId?S.digital.find(x=>x.id===editId)?.createdAt:new Date().toISOString()};
    if(editId)S.digital=S.digital.map(x=>x.id===editId?item:x);else S.digital.push(item);
    Activity.log((editId?'Edited':'Added')+' account',name);Store.save();Modal.close();this.render();Toast.show(`${editId?'Updated':'Added'}: ${name}`,'success');
  },
  detail(id){const d=S.digital.find(x=>x.id===id);if(!d)return;Modal.open(d.serviceName,`<div>${[['Service',d.serviceName],['Category',d.category||'—'],['URL',d.url||'—'],['Username',d.username?'••••':'-',d.username],['Email',d.email||'—'],['Password Hint',d.pwdHint||'—'],['2FA',d.twoFA||'None'],['2FA Active',d.twoFAEnabled?'Yes':'No'],['Verification',d.verificationStatus||'—'],['Balance',d.balance?d.balance+' '+d.currency:'—'],['Plan',d.plan||'—'],['Notes',d.notes||'—']].map(([k,v,s])=>U.drRow(k,v,s)).join('')}</div>`,`<button type="button" class="btn btn-g" onclick="Modal.close()">Close</button><button type="button" class="btn btn-p" onclick="Digital.edit('${id}');Modal.close()">Edit</button>`);},
  edit(id){const d=S.digital.find(x=>x.id===id);if(!d)return;Modal.open('Edit Account',this.form(d),`<button type="button" class="btn btn-g" onclick="Modal.close()">Cancel</button><button type="button" class="btn btn-d btn-sm" onclick="Digital.del('${id}',true)">Delete</button><button type="button" class="btn btn-p" onclick="Digital.save('${id}')">Update</button>`);setTimeout(()=>{const cur=document.getElementById('df-cur');if(cur)cur.value=d.currency||'USD';const em=document.getElementById('df-email');if(em){if(S.emails.find(e=>e.email===d.email))em.value=d.email;else{em.value='custom';const cw=document.getElementById('df-customWrap');if(cw)cw.style.display='';}}},60);},
  del(id,fm=false){if(!window.__vos_confirm('Move to Trash?'))return;const d=S.digital.find(x=>x.id===id);if(!d)return;S.trash.push({id:U.id(),type:'digital',data:d,deletedAt:new Date().toISOString()});S.digital=S.digital.filter(x=>x.id!==id);Activity.log('Trashed account',d.serviceName);Store.save();if(fm)Modal.close();this.render();Toast.show(`Moved to Trash — <button type="button" class="cpbtn" onclick="Trash.restore('${S.trash[S.trash.length-1].id}');this.closest('.toast').remove()">Undo</button>`,'info',6000);}
};
document.addEventListener('change',e=>{if(e.target.id==='df-email'){const w=document.getElementById('df-customWrap');if(w)w.style.display=e.target.value==='custom'?'':'none';}});
