const Emails={
  render(){
    const q=(document.getElementById('emailQ')?.value||'').toLowerCase();
    const data=S.emails.filter(e=>!q||JSON.stringify(e).toLowerCase().includes(q));
    const el=document.getElementById('emailItems');if(!el)return;
    if(!data.length){el.innerHTML=`<div class="empty-ios"><div class="ei-ic">📧</div><div class="ei-title">No Email Accounts</div><div class="ei-sub">Manage all your email identities — personal, business, recovery and more</div><button class="btn btn-p" onclick="Emails.openAdd()">📧 Add Email</button></div>`;return;}
    const byPurpose={};data.forEach(e=>{const k=e.purpose||'Other';(byPurpose[k]=byPurpose[k]||[]).push(e);});
    el.innerHTML=Object.entries(byPurpose).map(([p,items])=>`<div class="sdiv">${p} (${items.length})</div>${items.map(e=>{const prov=EMAIL_PROVIDERS.find(x=>x.n===e.provider)||EMAIL_PROVIDERS.at(-1);const sec=e.mfaEnabled&&e.passkeyEnabled?'ok':e.mfaEnabled?'warn':'err';return `<div class="entry"><div class="entry-main"><div class="entry-ic" style="background:${prov.color}22;font-size:18px">${prov.ic}</div><div class="entry-body"><div class="entry-name">${e.email}</div><div class="entry-sub">${e.provider||''} ${e.purpose?'· '+e.purpose:''}</div><div class="entry-meta"><span class="badge ${sec==='ok'?'b-ok':sec==='warn'?'b-warn':'b-err'}">${sec==='ok'?'🔒 Secure':sec==='warn'?'⚠️ 2FA':'❌ No 2FA'}</span> ${e.passkeyEnabled?'<span class="badge b-ok">Passkey</span>':''} ${e.linkedServices?`<span class="badge b-muted">🔗 linked</span>`:''}</div></div><div class="entry-acts"><button class="icb" onclick="Emails.detail('${e.id}')">👁️</button><button class="icb" onclick="Emails.edit('${e.id}')">✏️</button><button class="icb del" onclick="Emails.del('${e.id}')">🗑️</button></div></div></div>`;}).join('')}`).join('');
  },
  openAdd(){Modal.open('📧 Add Email Account',this.form(),`<button class="btn btn-g" onclick="Modal.close()">Cancel</button><button class="btn btn-p" onclick="Emails.save()">Save</button>`);},
  form(e={}){
    return `<div class="fg"><label class="fl">Email Address *</label><input class="inp" id="emf-addr" value="${e.email||''}" type="email" placeholder="you@example.com"></div>
    <div class="fr"><div class="fg"><label class="fl">Provider</label><datalist id="emfProvDL">${EMAIL_PROVIDERS.map(p=>`<option value="${p.n}">`).join('')}</datalist><input class="inp" id="emf-prov" value="${e.provider||''}" list="emfProvDL" placeholder="Gmail, Outlook, ProtonMail..."></div><div class="fg"><label class="fl">Purpose</label><datalist id="emfPurpDL"><option>Personal</option><option>Business</option><option>Work</option><option>Spam / Junk</option><option>Recovery</option><option>Anonymous</option><option>Family</option><option>School</option><option>Shopping</option><option>AI Tools</option></datalist><input class="inp" id="emf-purp" value="${e.purpose||''}" list="emfPurpDL" placeholder="Personal, Business..."></div></div>
    <div class="fg"><label class="fl">Password Hint</label><input class="inp" id="emf-pwd" value="${e.pwdHint||''}" placeholder="e.g. 'Usual + capital + !23'"></div>
    <div class="fr"><div class="fg"><label class="fl">Recovery Email</label><input class="inp" id="emf-rec" value="${e.recoveryEmail||''}" placeholder="backup@email.com"></div><div class="fg"><label class="fl">Recovery Phone</label><input class="inp" id="emf-rph" value="${e.recoveryPhone||S.user.phone||''}" placeholder="+44..."></div></div>
    <div class="fr"><div class="fg"><label class="fl">2FA Method</label><datalist id="emf2faDL"><option>None</option><option>SMS</option><option>Authenticator App</option><option>Email</option><option>Hardware Key</option><option>Passkey</option></datalist><input class="inp" id="emf-2fa" value="${e.twoFA||'None'}" list="emf2faDL" placeholder="SMS, Authenticator..."></div><div class="fg"><label class="fl">Authenticator App</label><datalist id="emfAuthDL"><option>Google Authenticator</option><option>Authy</option><option>Microsoft Authenticator</option><option>1Password</option><option>Bitwarden</option><option>Apple Passwords</option></datalist><input class="inp" id="emf-auth" value="${e.authenticatorApp||''}" list="emfAuthDL" placeholder="Google Auth, Authy..."></div></div>
    <div style="background:var(--glass);border:1px solid var(--border);border-radius:var(--rsm);padding:12px;margin-bottom:12px">
      <div style="font-size:10px;font-weight:700;color:var(--text2);margin-bottom:10px;letter-spacing:.5px">SECURITY STATUS</div>
      <div style="display:flex;flex-direction:column;gap:9px">
        <label style="display:flex;align-items:center;justify-content:space-between;font-size:13px">🔐 MFA / 2FA Enabled<label class="tog"><input type="checkbox" id="emf-mfa" ${e.mfaEnabled?'checked':''}><span class="ts"></span></label></label>
        <label style="display:flex;align-items:center;justify-content:space-between;font-size:13px">🗝️ Passkey Enabled<label class="tog"><input type="checkbox" id="emf-pk" ${e.passkeyEnabled?'checked':''}><span class="ts"></span></label></label>
        <label style="display:flex;align-items:center;justify-content:space-between;font-size:13px">💾 Backup Codes Stored<label class="tog"><input type="checkbox" id="emf-bk" ${e.backupCodesStored?'checked':''}><span class="ts"></span></label></label>
      </div>
    </div>
    <div class="fg"><label class="fl">Linked Services (comma-separated)</label><input class="inp" id="emf-subs" value="${e.linkedServices||''}" placeholder="Netflix, LinkedIn, GitHub..."></div>
    <div class="fg"><label class="fl">Notes</label><textarea class="inp" id="emf-notes" rows="2">${e.notes||''}</textarea></div>
    <div class="fg"><label class="fl">Tags</label>${U.tags(e.tags||[])}</div>`;
  },
  save(editId=null){
    const addr=document.getElementById('emf-addr').value.trim();
    if(!addr||!addr.includes('@')){Toast.show('Valid email required','warning');return;}
    if(!editId){const dup=checkDuplicate('email',{email:addr});if(dup.isDuplicate&&!window.__vos_confirm(dup.message))return;}
    const item={id:editId||U.id(),email:addr,provider:document.getElementById('emf-prov').value.trim(),purpose:document.getElementById('emf-purp').value.trim(),pwdHint:document.getElementById('emf-pwd').value.trim(),recoveryEmail:document.getElementById('emf-rec').value.trim(),recoveryPhone:document.getElementById('emf-rph').value.trim(),twoFA:document.getElementById('emf-2fa').value.trim(),authenticatorApp:document.getElementById('emf-auth').value.trim(),mfaEnabled:document.getElementById('emf-mfa').checked,passkeyEnabled:document.getElementById('emf-pk').checked,backupCodesStored:document.getElementById('emf-bk').checked,linkedServices:document.getElementById('emf-subs').value.trim(),notes:document.getElementById('emf-notes').value.trim(),tags:U.getTags(),createdAt:editId?S.emails.find(x=>x.id===editId)?.createdAt:new Date().toISOString()};
    if(editId)S.emails=S.emails.map(x=>x.id===editId?item:x);else S.emails.push(item);
    Activity.log((editId?'Edited':'Added')+' email',addr);Store.save();Modal.close();this.render();Toast.show(`${editId?'Updated':'Added'}: ${addr}`,'success');
  },
  detail(id){const e=S.emails.find(x=>x.id===id);if(!e)return;Modal.open(`📧 ${e.email}`,`<div>${[['Email',e.email],['Provider',e.provider||'—'],['Purpose',e.purpose||'—'],['Password Hint',e.pwdHint||'—'],['Recovery Email',e.recoveryEmail?'••••':'-',e.recoveryEmail],['Recovery Phone',e.recoveryPhone?'••••':'-',e.recoveryPhone],['2FA',e.twoFA||'None'],['Authenticator',e.authenticatorApp||'—'],['MFA Enabled',e.mfaEnabled?'✅ Yes':'❌ No'],['Passkey',e.passkeyEnabled?'✅ Yes':'❌ No'],['Backup Codes',e.backupCodesStored?'✅ Stored':'—'],['Linked Services',e.linkedServices||'—'],['Notes',e.notes||'—']].map(([k,v,s])=>U.drRow(k,v,s)).join('')}</div>`,`<button class="btn btn-g" onclick="Modal.close()">Close</button><button class="btn btn-p" onclick="Emails.edit('${id}');Modal.close()">Edit</button>`);},
  edit(id){const e=S.emails.find(x=>x.id===id);if(!e)return;Modal.open('✏️ Edit Email',this.form(e),`<button class="btn btn-g" onclick="Modal.close()">Cancel</button><button class="btn btn-d btn-sm" onclick="Emails.del('${id}',true)">Delete</button><button class="btn btn-p" onclick="Emails.save('${id}')">Update</button>`);},
  del(id,fm=false){if(!window.__vos_confirm('Move to Trash?'))return;const e=S.emails.find(x=>x.id===id);if(!e)return;S.trash.push({id:U.id(),type:'emails',data:e,deletedAt:new Date().toISOString()});S.emails=S.emails.filter(x=>x.id!==id);Activity.log('Trashed email',e.email);Store.save();if(fm)Modal.close();this.render();Toast.show(`Moved to Trash — <button class="cpbtn" onclick="Trash.restore('${S.trash[S.trash.length-1].id}');this.closest('.toast').remove()">Undo</button>`,'info',6000);}
};
