const Exp={
  render(){
    const f=S.expF;
    const chips=[['all','All'],['Streaming','🎬 Stream'],['Music','🎵 Music'],['VPN','🔒 VPN'],['Cloud','☁️ Cloud'],['Fitness','💪 Fitness'],['Gaming','🎮 Gaming'],['AI','🤖 AI'],['Productivity','💼 Prod'],['Security','🔑 Security'],['News','📰 News'],['Other','📦 Other']];
    const ci=document.getElementById('expChips');
    if(ci)ci.innerHTML=chips.map(([v,l])=>`<div class="chip${v===f?' on':''}" onclick="S.expF='${v}';Exp.render()">${l}</div>`).join('');
    const toMonthlyPKR=e=>{const a=parseFloat(String(e.amount||0).replace(/,/g,''))||0;const freq=(e.frequency||e.cycle||'monthly').toLowerCase();let monthly=a;if(freq.includes('year')||freq.includes('annual'))monthly=a/12;else if(freq.includes('week'))monthly=a*52/12;else if(freq.includes('quarter'))monthly=a/3;else if(freq.includes('one')||freq.includes('once'))monthly=0;return typeof CurrencyEngine!=='undefined'?CurrencyEngine.toBase(monthly,e.currency||S.user.currency||'PKR'):monthly;};
    const toMonthly=e=>{const a=parseFloat(String(e.amount||0).replace(/,/g,''))||0;const freq=(e.frequency||e.cycle||'monthly').toLowerCase();if(freq.includes('year')||freq.includes('annual'))return a/12;if(freq.includes('week'))return a*52/12;if(freq.includes('quarter'))return a/3;if(freq.includes('one')||freq.includes('once'))return 0;return a;};
    const data=S.expenses.filter(e=>f==='all'||e.category===f);
    const active=data.filter(e=>e.active);
    const totalPKR=active.reduce((a,e)=>a+toMonthlyPKR(e),0);
    const total=typeof CurrencyEngine!=='undefined'?CurrencyEngine.fromBase(totalPKR,S.user.currency||'PKR'):totalPKR;
    const yearlyTotal=total*12;
    const sm=document.getElementById('expSummary');
    if(sm&&S.expenses.length>0){
      const allActive=S.expenses.filter(e=>e.active);
      const byCat={};allActive.forEach(e=>{const c=e.category||'Other';byCat[c]=(byCat[c]||0)+toMonthlyPKR(e);});
      const top3=Object.entries(byCat).sort((a,b)=>b[1]-a[1]).slice(0,3);
      const paused=S.expenses.filter(e=>!e.active).length;
      const CAT_COLORS={'Streaming':'#e91e8c','Music':'#9c27b0','Fitness':'#4caf50','Gaming':'#ff9800','AI':'#5b8dee','Productivity':'#00bcd4','Cloud':'#03a9f4','VPN':'#607d8b','Security':'#f44336','News':'#795548','Telecom':'#ff5722','Housing':'#8bc34a','Transport':'#ffc107','Food':'#ff6b35','Other':'#9e9e9e'};
      const catArr=Object.entries(byCat).sort((a,b)=>b[1]-a[1]).slice(0,6);
      const catTotal=catArr.reduce((a,[,v])=>a+v,0)||1;
      const userCur=S.user.currency||'PKR';
      const donutSVG=catArr.length>1?(()=>{const cx=80,cy=80,r=60,circ=2*Math.PI*r;let offset=0;const segments=catArr.map(([cat,val])=>{const pct=val/catTotal,dash=pct*circ,color=CAT_COLORS[cat]||'#9e9e9e';const seg=`<circle cx="${cx}" cy="${cy}" r="${r}" fill="none" stroke="${color}" stroke-width="20" stroke-dasharray="${dash.toFixed(1)} ${circ.toFixed(1)}" stroke-dashoffset="${(-offset*circ).toFixed(1)}" transform="rotate(-90 ${cx} ${cy})" opacity="0.9"/>`;offset+=pct;return{seg,cat,val,color};});const legend=segments.map(({cat,val,color})=>`<div style="display:flex;align-items:center;gap:6px;margin-bottom:4px"><div style="width:10px;height:10px;border-radius:2px;background:${color};flex-shrink:0"></div><div style="font-size:11px;color:var(--text2);flex:1">${cat}</div><div style="font-size:11px;font-weight:700;color:var(--text)">${userCur} ${Math.round(typeof CurrencyEngine!=='undefined'?CurrencyEngine.fromBase(val,userCur):val).toLocaleString()}</div></div>`).join('');return `<div style="background:var(--glass);border:1px solid var(--border);border-radius:16px;padding:16px;margin-bottom:14px;display:flex;gap:16px;align-items:center"><div style="flex-shrink:0"><svg width="160" height="160" viewBox="0 0 160 160"><circle cx="80" cy="80" r="60" fill="none" stroke="rgba(255,255,255,.06)" stroke-width="20"/>${segments.map(s=>s.seg).join('')}<text x="80" y="76" text-anchor="middle" font-size="13" font-weight="900" fill="var(--text)">${userCur} ${Math.round(total).toLocaleString()}</text><text x="80" y="92" text-anchor="middle" font-size="9" fill="var(--text3)">per month</text></svg></div><div style="flex:1">${legend}</div></div>`;})():'';
      sm.innerHTML=`<div class="widget" style="margin-bottom:12px"><div class="wh"><span>📋</span>Monthly Overview</div><div style="display:flex;gap:0;flex-wrap:wrap"><div style="flex:1;min-width:80px;padding:4px 8px 4px 0;border-right:1px solid var(--border)"><div style="font-size:10px;color:var(--text3);margin-bottom:2px">Monthly</div><div style="font-size:24px;font-weight:900;color:var(--accent)">${U.fmt(Math.round(total))}<span style="font-size:12px;font-weight:400;color:var(--text3)"> ${S.user.currency}</span></div></div><div style="flex:1;min-width:80px;padding:4px 8px"><div style="font-size:10px;color:var(--text3);margin-bottom:2px">Yearly</div><div style="font-size:18px;font-weight:700">${U.fmt(Math.round(yearlyTotal))}</div></div><div style="flex:1;min-width:80px;padding:4px 8px;border-left:1px solid var(--border)"><div style="font-size:10px;color:var(--text3);margin-bottom:2px">Active / Paused</div><div style="font-size:18px;font-weight:700">${active.length}<span style="font-size:12px;font-weight:400;color:var(--text3)"> / ${paused}</span></div></div></div>${top3.length?`<div style="border-top:1px solid var(--border);padding:8px 14px"><div style="font-size:10px;font-weight:700;color:var(--text3);margin-bottom:6px;text-transform:uppercase;letter-spacing:.5px">Top Categories</div><div style="display:flex;flex-direction:column;gap:4px">${top3.map(([cat,amt])=>`<div style="display:flex;justify-content:space-between;align-items:center"><span style="font-size:12px;color:var(--text2)">${cat}</span><span style="font-size:12px;font-weight:700;color:var(--accent)">${U.fmt(Math.round(typeof CurrencyEngine!=='undefined'?CurrencyEngine.fromBase(amt,userCur):amt))}</span></div>`).join('')}</div></div>`:''}
      </div>${donutSVG}`;
    }else if(sm)sm.innerHTML='';
    const el=document.getElementById('expItems');if(!el)return;
    if(!data.length){el.innerHTML=`<div class="empty"><div class="empty-ic">📋</div><h3>No expenses yet</h3><p>Track all your recurring bills and subscriptions — Netflix, Spotify, gym, insurance, rent and more</p><div class="empty-guide"><div class="guide-step"><div class="gst-num">1</div><div class="gst-body"><h4>Add a subscription</h4><p>Type any service name — Netflix, NordVPN, gym etc.</p></div></div><div class="guide-step"><div class="gst-num">2</div><div class="gst-body"><h4>Link your payment source</h4><p>Connect to the card or bank it's billed from</p></div></div><div class="guide-step"><div class="gst-num">3</div><div class="gst-body"><h4>Pause when inactive</h4><p>Toggle off subscriptions you've paused without deleting</p></div></div></div><button class="btn btn-p" style="margin-top:14px" onclick="Exp.openAdd()">📋 Add First Expense</button></div>`;return;}
    el.innerHTML=data.map(e=>`<div class="entry"><div class="entry-main"><div class="entry-ic" style="font-size:20px;background:transparent">${e.icon||'📋'}</div><div class="entry-body"><div class="entry-name">${e.name}${!e.active?'<span class="badge b-muted" style="margin-left:6px;font-size:9px">PAUSED</span>':''}</div><div class="entry-sub">${e.category||''} ${e.from?'· '+e.from:''} ${e.cycle&&e.cycle!=='monthly'?'· '+e.cycle:''}</div><div class="entry-meta"><span class="badge b-acc">${e.currency||S.user.currency} ${U.fmt(parseFloat(e.amount)||0)}/mo</span>${e.renewalDate?`<span class="badge b-warn">🗓 ${e.renewalDate}</span>`:''}</div></div><div class="entry-acts"><label class="tog" style="margin-right:2px"><input type="checkbox" ${e.active?'checked':''} onchange="Exp.toggle('${e.id}',this.checked)"><span class="ts"></span></label><button class="icb" onclick="Exp.edit('${e.id}')">✏️</button><button class="icb del" onclick="Exp.del('${e.id}')">🗑️</button></div></div></div>`).join('');
  },
  toggle(id,v){const e=S.expenses.find(x=>x.id===id);if(e){e.active=v;Store.save();Exp.render();}},
  openAdd(){Modal.open('📋 Add Expense / Subscription',this.form(),`<button class="btn btn-g" onclick="Modal.close()">Cancel</button><button class="btn btn-p" onclick="Exp.save()">Save</button>`);setTimeout(()=>{const el=document.getElementById('ef-amt');if(el)U.numInput(el,S.user.currency||'PKR');},60);},
  form(e={}){
    return `<datalist id="subDL2">${SUBS_DB.map(s=>`<option value="${s.n}">`).join('')}</datalist>
    <div class="fg"><label class="fl">Name *</label><input class="inp" id="ef-name" value="${e.name||''}" list="subDL2" placeholder="Netflix, Gym, Rent, NordVPN..." oninput="Exp.autofill(this.value)" autocomplete="off"></div>
    <div class="fr"><div class="fg"><label class="fl">Category</label><datalist id="efCatDL"><option>Streaming</option><option>Music</option><option>VPN</option><option>Cloud</option><option>Fitness</option><option>Gaming</option><option>AI</option><option>Productivity</option><option>Security</option><option>News</option><option>Utilities</option><option>Rent</option><option>Insurance</option><option>Other</option></datalist><input class="inp" id="ef-cat" value="${e.category||''}" list="efCatDL" placeholder="Streaming, Fitness..."></div><div class="fg"><label class="fl">Icon (emoji)</label><input class="inp" id="ef-icon" value="${e.icon||'📋'}" placeholder="📋" style="font-size:20px;text-align:center;width:80px"></div></div>
    <div class="fr"><div class="fg"><label class="fl">Amount / month *</label><input class="inp num-inp" id="ef-amt" type="text" inputmode="decimal" pattern="[0-9,\\.]*" value="${e.amount||''}" placeholder="9.99"></div><div class="fg"><label class="fl">Currency</label><select class="inp" id="ef-cur">${U.currencies()}</select></div></div>
    <div class="fr"><div class="fg"><label class="fl">Billing Cycle</label><datalist id="efCycleDL"><option>Daily</option><option>Weekly</option><option>Monthly</option><option>Quarterly</option><option>Every 6 months</option><option>Yearly / Annual</option><option>One-time</option></datalist><input class="inp" id="ef-cycle" value="${e.cycle||''}" list="efCycleDL" placeholder="monthly, yearly..."></div><div class="fg"><label class="fl">Renewal Date</label><input class="inp" id="ef-ren" value="${e.renewalDate||''}" type="date"></div></div>
    <div class="fg"><label class="fl">Billed From (Card / Bank)</label><select class="inp" id="ef-from"><option value="">— Not linked —</option>${S.cards.map(c=>`<option value="💳 ${c.cardName} ${c.last4?'****'+c.last4:''}"${e.from===`💳 ${c.cardName} ${c.last4?'****'+c.last4:''}`?' selected':''}>💳 ${c.cardName} ${c.last4?'****'+c.last4:''}</option>`).join('')}${S.banks.map(b=>`<option value="🏦 ${b.bankName}"${e.from===`🏦 ${b.bankName}`?' selected':''}>🏦 ${b.bankName} (${b.currency})</option>`).join('')}</select></div>
    <div class="fg"><label class="fl">Notes</label><input class="inp" id="ef-notes" value="${e.notes||''}" placeholder="Account email, plan details..."></div>
    <label style="display:flex;align-items:center;gap:8px;cursor:pointer;font-size:13px;margin-top:4px"><input type="checkbox" id="ef-active" ${e.active!==false?'checked':''}> Active (counts in monthly total)</label>`;
  },
  autofill(n){const s=SUBS_DB.find(x=>x.n.toLowerCase()===n.toLowerCase());if(!s)return;const c=document.getElementById('ef-cat');const i=document.getElementById('ef-icon');if(c&&!c.value)c.value=s.c;if(i&&i.value==='📋')i.value=s.ic;},
  save(editId=null){
    const name=document.getElementById('ef-name').value.trim();
    if(!name){Toast.show('Name required','warning');return;}
    const item={id:editId||U.id(),name,category:document.getElementById('ef-cat').value.trim(),icon:document.getElementById('ef-icon').value.trim()||'📋',amount:parseFloat((document.getElementById('ef-amt').value||'').replace(/,/g,''))||0,currency:document.getElementById('ef-cur').value,from:document.getElementById('ef-from').value,cycle:document.getElementById('ef-cycle').value||'monthly',renewalDate:document.getElementById('ef-ren').value,notes:document.getElementById('ef-notes').value.trim(),active:document.getElementById('ef-active').checked,createdAt:editId?S.expenses.find(x=>x.id===editId)?.createdAt:new Date().toISOString()};
    if(editId)S.expenses=S.expenses.map(x=>x.id===editId?item:x);else S.expenses.push(item);
    Activity.log((editId?'Edited':'Added')+' expense',name);Store.save();Modal.close();this.render();Toast.show(`${editId?'Updated':'Added'}: ${name}`,'success');
  },
  edit(id){const e=S.expenses.find(x=>x.id===id);if(!e)return;Modal.open('✏️ Edit Expense',this.form(e),`<button class="btn btn-g" onclick="Modal.close()">Cancel</button><button class="btn btn-d btn-sm" onclick="Exp.del('${id}',true)">Delete</button><button class="btn btn-p" onclick="Exp.save('${id}')">Update</button>`);setTimeout(()=>{const c=document.getElementById('ef-cur');if(c)c.value=e.currency||S.user.currency||'GBP';},60);},
  del(id,fm=false){if(!window.__vos_confirm('Move to Trash?'))return;const e=S.expenses.find(x=>x.id===id);if(!e)return;S.trash.push({id:U.id(),type:'expenses',data:e,deletedAt:new Date().toISOString()});S.expenses=S.expenses.filter(x=>x.id!==id);Activity.log('Trashed expense',e.name);Store.save();if(fm)Modal.close();this.render();Toast.show(`Moved to Trash — <button class="cpbtn" onclick="Trash.restore('${S.trash[S.trash.length-1].id}');this.closest('.toast').remove()">Undo</button>`,'info',6000);}
};
