const Gadgets={
  render(){
    const f=S.gF;
    const chips=[['all','All'],['Phone','📱 Phones'],['Tablet','📲 Tablets'],['Laptop','💻 Laptops'],['Desktop','🖥️ Desktop'],['Wearable','⌚ Wearables'],['Audio','🎧 Audio'],['Gaming','🎮 Gaming'],['Smart Home','🏠 Smart Home'],['Camera','📷 Camera'],['Network','📡 Network'],['Storage','💾 Storage']];
    const ci=document.getElementById('gChips');
    if(ci)ci.innerHTML=chips.map(([v,l])=>`<div class="chip${v===f?' on':''}" onclick="S.gF='${v}';Gadgets.render()">${l}</div>`).join('');
    const data=S.gadgets.filter(g=>f==='all'||g.category===f);
    const el=document.getElementById('gItems');if(!el)return;
    if(!data.length){el.innerHTML=`<div class="empty"><div class="empty-ic">💻</div><h3>No devices yet</h3><p>Track iPhones, MacBooks, iPads, AirPods, watches, gaming consoles and more — including serial numbers, warranty, IMEI and security details</p><button class="btn btn-p" style="margin-top:12px" onclick="Gadgets.openAdd()">💻 Add Device</button></div>`;return;}
    const byCat={};data.forEach(g=>{(byCat[g.category||'Other']=byCat[g.category||'Other']||[]).push(g);});
    el.innerHTML=Object.entries(byCat).map(([cat,items])=>`<div class="sdiv">${cat} (${items.length})</div>${items.map(g=>{const warExpired=g.warranty&&new Date(g.warranty)<new Date();const warSoon=g.warranty&&!warExpired&&new Date(g.warranty)<new Date(Date.now()+30*864e5);return `<div class="entry"><div class="entry-main"><div class="entry-ic">${g.ic||'💻'}</div><div class="entry-body"><div class="entry-name">${g.name}${g.storage?' <span class="badge b-muted">'+g.storage+'</span>':''}</div><div class="entry-sub">${g.brand||''} ${g.color?'· '+g.color:''} ${g.condition?'· '+g.condition:''}</div><div class="entry-meta">${g.purchasePrice?`<span class="badge b-acc">${g.currency||''} ${U.fmt(g.purchasePrice)}</span>`:''} ${warExpired?'<span class="badge b-err">Warranty expired</span>':warSoon?'<span class="badge b-warn">Warranty expiring</span>':g.warranty?'<span class="badge b-ok">Warranty ✓</span>':''} ${g.findMyEnabled?'<span class="badge b-ok">Find My ✓</span>':''} ${g.ownership==='business'?'<span class="badge b-warn">🏢</span>':''}</div></div><div class="entry-acts"><button class="icb" onclick="Gadgets.detail('${g.id}')">👁️</button><button class="icb" onclick="Gadgets.edit('${g.id}')">✏️</button><button class="icb del" onclick="Gadgets.del('${g.id}')">🗑️</button></div></div></div>`;}).join('')}`).join('');
  },
  openAdd(){Modal.open('💻 Add Device / Gadget',this.form(),`<button class="btn btn-g" onclick="Modal.close()">Cancel</button><button class="btn btn-p" onclick="Gadgets.save()">Save</button>`);},
  form(g={}){
    return `<datalist id="gDL">${ALL_GADGET_MODELS.map(m=>`<option value="${m}">`).join('')}</datalist>
    <div class="fg"><label class="fl">Device Name *</label><input class="inp" id="gf-name" value="${g.name||''}" list="gDL" placeholder="iPhone 16 Pro Max, MacBook Pro M4..." oninput="Gadgets.autofill(this.value)" autocomplete="off"></div>
    <div class="fr"><div class="fg"><label class="fl">Brand</label><datalist id="gfBrandDL"><option>Apple</option><option>Samsung</option><option>Google</option><option>Sony</option><option>LG</option><option>OnePlus</option><option>Xiaomi</option><option>Huawei</option><option>Microsoft</option><option>Dell</option><option>HP</option><option>Lenovo</option><option>ASUS</option></datalist><input class="inp" id="gf-brand" value="${g.brand||''}" list="gfBrandDL" placeholder="Apple, Samsung, Sony..."></div><div class="fg"><label class="fl">Category</label><datalist id="gfCatDL"><option>Phone</option><option>Tablet</option><option>Laptop</option><option>Desktop</option><option>Wearable</option><option>Audio</option><option>Gaming</option><option>Smart Home</option><option>Camera</option><option>Network</option><option>Storage</option><option>Accessory</option><option>Other</option></datalist><input class="inp" id="gf-cat" value="${g.category||''}" list="gfCatDL" placeholder="Phone, Laptop..."></div></div>
    <div class="fr"><div class="fg"><label class="fl">Storage / RAM</label><datalist id="gfStorDL"><option>64GB</option><option>128GB</option><option>256GB</option><option>512GB</option><option>1TB</option><option>2TB</option><option>8GB RAM</option><option>16GB RAM</option><option>32GB RAM</option></datalist><input class="inp" id="gf-stor" value="${g.storage||''}" list="gfStorDL" placeholder="256GB, 16GB RAM..."></div><div class="fg"><label class="fl">Colour</label><input class="inp" id="gf-col" value="${g.color||''}" placeholder="Natural Titanium, Midnight..."></div></div>
    <div class="fg"><label class="fl">Specific Model / SKU</label><input class="inp" id="gf-model" value="${g.model||''}" placeholder="e.g. A3293 / MYE13LL/A"></div>
    <div class="fr"><div class="fg"><label class="fl">Serial Number</label><input class="inp" id="gf-serial" value="${g.serialNum||''}" placeholder="Serial #"></div><div class="fg"><label class="fl">IMEI (phones/tablets)</label><input class="inp" id="gf-imei" value="${g.imei||''}" placeholder="15-digit IMEI"></div></div>
    <div class="fr"><div class="fg"><label class="fl">Purchase Price</label><input class="inp" id="gf-price" value="${g.purchasePrice||''}" type="number" placeholder="0"></div><div class="fg"><label class="fl">Currency</label><select class="inp" id="gf-cur">${U.currencies()}</select></div></div>
    <div class="fr"><div class="fg"><label class="fl">Purchase Date</label><input class="inp" id="gf-pdate" value="${g.purchaseDate||''}" type="date"></div><div class="fg"><label class="fl">Warranty Expiry</label><input class="inp" id="gf-warr" value="${g.warranty||''}" type="date"></div></div>
    <div class="fr"><div class="fg"><label class="fl">Resale Value Now</label><input class="inp" id="gf-rval" value="${g.resaleValue||''}" type="number" placeholder="0"></div><div class="fg"><label class="fl">Condition</label><datalist id="gfCondDL"><option>New</option><option>Excellent</option><option>Good</option><option>Fair</option><option>Poor</option><option>Refurbished</option></datalist><input class="inp" id="gf-cond" value="${g.condition||''}" list="gfCondDL" placeholder="Excellent, Good..."></div></div>
    <div class="fr"><div class="fg"><label class="fl">Unlock / Login Method</label><datalist id="gfUnlockDL"><option>Face ID</option><option>Touch ID</option><option>PIN</option><option>Pattern</option><option>Password</option><option>Fingerprint</option><option>None</option></datalist><input class="inp" id="gf-unlock" value="${g.unlockMethod||''}" list="gfUnlockDL" placeholder="Face ID, PIN..."></div><div class="fg"><label class="fl">Password Hint</label><input class="inp" id="gf-lockpwd" value="${g.lockPwdHint||''}" placeholder="Hint only — never full password"></div></div>
    <div class="fr"><div class="fg"><label class="fl">Linked Apple ID / Google</label><input class="inp" id="gf-acid" value="${g.linkedAccount||''}" placeholder="email@icloud.com"></div><div class="fg"><label class="fl">Find My / Find My Device</label><datalist id="gfFindDL"><option>On</option><option>Off</option><option>Not applicable</option></datalist><input class="inp" id="gf-findmy" value="${g.findMyEnabled?'On':'Off'}" list="gfFindDL" placeholder="On, Off..."></div></div>
    <div class="fr"><div class="fg"><label class="fl">Seller / Retailer</label><input class="inp" id="gf-seller" value="${g.seller||''}" placeholder="Apple Store, Amazon..."></div><div class="fg"><label class="fl">Insurance Policy #</label><input class="inp" id="gf-ins" value="${g.insurancePolicyNum||''}" placeholder="Policy number"></div></div>
    <div class="fr"><div class="fg"><label class="fl">Ownership</label><select class="inp" id="gf-own"><option value="personal"${g.ownership!=='business'?' selected':''}>👤 Personal</option><option value="business"${g.ownership==='business'?' selected':''}>🏢 Business</option></select></div><div class="fg"><label class="fl">Assigned Staff (work devices)</label><input class="inp" id="gf-staff" value="${g.staffAssigned||''}" placeholder="Staff name"></div></div>
    <div class="fg"><label class="fl">Notes</label><textarea class="inp" id="gf-notes" rows="2">${g.notes||''}</textarea></div>
    <div class="fg"><label class="fl">Tags</label>${U.tags(g.tags||[])}</div>`;
  },
  autofill(name){
    const brand=document.getElementById('gf-brand');const cat=document.getElementById('gf-cat');
    if(!brand||!cat)return;
    const n=name.toLowerCase();
    if(IPHONE_MODELS.some(m=>m.toLowerCase()===n)||n.includes('iphone')){if(!brand.value)brand.value='Apple';cat.value='Phone';}
    else if(MACBOOK_MODELS.some(m=>m.toLowerCase()===n)||n.includes('macbook')){if(!brand.value)brand.value='Apple';cat.value='Laptop';}
    else if(n.includes('ipad')){if(!brand.value)brand.value='Apple';cat.value='Tablet';}
    else if(n.includes('airpods')||n.includes('airpod')){if(!brand.value)brand.value='Apple';cat.value='Audio';}
    else if(n.includes('apple watch')){if(!brand.value)brand.value='Apple';cat.value='Wearable';}
    else if(n.includes('imac')||n.includes('mac mini')||n.includes('mac pro')||n.includes('mac studio')){if(!brand.value)brand.value='Apple';cat.value='Desktop';}
    else if(SAMSUNG_MODELS.some(m=>m.toLowerCase()===n)||n.includes('galaxy')){if(!brand.value)brand.value='Samsung';cat.value=n.includes('watch')?'Wearable':'Phone';}
    else if(n.includes('ps5')||n.includes('playstation')){if(!brand.value)brand.value='Sony';cat.value='Gaming';}
    else if(n.includes('xbox')){if(!brand.value)brand.value='Microsoft';cat.value='Gaming';}
  },
  save(editId=null){
    const name=document.getElementById('gf-name').value.trim();if(!name){Toast.show('Device name required','warning');return;}
    const g=id=>{const e=document.getElementById(id);return e?e.value:''};
    const catVal=g('gf-cat');
    const icMap={'Phone':'📱','Tablet':'📲','Laptop':'💻','Desktop':'🖥️','Wearable':'⌚','Audio':'🎧','Gaming':'🎮','Smart Home':'🏠','Camera':'📷','Network':'📡','Storage':'💾'};
    const item={id:editId||U.id(),name,brand:g('gf-brand'),category:catVal,storage:g('gf-stor'),color:g('gf-col'),model:g('gf-model'),serialNum:g('gf-serial'),imei:g('gf-imei'),purchasePrice:parseFloat(g('gf-price'))||0,currency:g('gf-cur'),purchaseDate:g('gf-pdate'),warranty:g('gf-warr'),resaleValue:parseFloat(g('gf-rval'))||0,condition:g('gf-cond'),unlockMethod:g('gf-unlock'),lockPwdHint:g('gf-lockpwd'),linkedAccount:g('gf-acid'),findMyEnabled:g('gf-findmy').toLowerCase()==='on',seller:g('gf-seller'),insurancePolicyNum:g('gf-ins'),ownership:g('gf-own'),staffAssigned:g('gf-staff'),notes:g('gf-notes'),tags:U.getTags(),ic:icMap[catVal]||'💻',createdAt:editId?S.gadgets.find(x=>x.id===editId)?.createdAt:new Date().toISOString()};
    if(editId)S.gadgets=S.gadgets.map(x=>x.id===editId?item:x);else S.gadgets.push(item);
    Activity.log((editId?'Edited':'Added')+' device',name);Store.save();Modal.close();this.render();Toast.show(`${editId?'Updated':'Added'}: ${name}`,'success');
  },
  detail(id){const g=S.gadgets.find(x=>x.id===id);if(!g)return;Modal.open(`${g.ic||'💻'} ${g.name}`,`<div>${[['Device',g.name],['Brand',g.brand||'—'],['Category',g.category||'—'],['Storage',g.storage||'—'],['Colour',g.color||'—'],['Model',g.model||'—'],['Serial No.',g.serialNum?'••••':'-',g.serialNum],['IMEI',g.imei?'•••':'-',g.imei],['Purchase Price',g.purchasePrice?U.fmt(g.purchasePrice)+' '+g.currency:'—'],['Purchase Date',g.purchaseDate||'—'],['Warranty',g.warranty?new Date(g.warranty).toLocaleDateString('en-GB'):'—'],['Resale Value',g.resaleValue?U.fmt(g.resaleValue):'—'],['Condition',g.condition||'—'],['Unlock',g.unlockMethod||'—'],['Lock Hint',g.lockPwdHint||'—'],['Linked Account',g.linkedAccount?'••••':'-',g.linkedAccount],['Find My',g.findMyEnabled?'✅ On':'Off'],['Insurance',g.insurancePolicyNum||'—'],['Seller',g.seller||'—'],['Notes',g.notes||'—']].map(([k,v,s])=>U.drRow(k,v,s)).join('')}</div>`,`<button class="btn btn-g" onclick="Modal.close()">Close</button><button class="btn btn-p" onclick="Gadgets.edit('${id}');Modal.close()">Edit</button>`);},
  edit(id){const g=S.gadgets.find(x=>x.id===id);if(!g)return;Modal.open('✏️ Edit Device',this.form(g),`<button class="btn btn-g" onclick="Modal.close()">Cancel</button><button class="btn btn-d btn-sm" onclick="Gadgets.del('${id}',true)">Delete</button><button class="btn btn-p" onclick="Gadgets.save('${id}')">Update</button>`);setTimeout(()=>{const cur=document.getElementById('gf-cur');const own=document.getElementById('gf-own');if(cur)cur.value=g.currency||'GBP';if(own)own.value=g.ownership||'personal';},60);},
  del(id,fm=false){if(!window.__vos_confirm('Move to Trash?'))return;const g=S.gadgets.find(x=>x.id===id);if(!g)return;S.trash.push({id:U.id(),type:'gadgets',data:g,deletedAt:new Date().toISOString()});S.gadgets=S.gadgets.filter(x=>x.id!==id);Activity.log('Trashed device',g.name);Store.save();if(fm)Modal.close();this.render();Toast.show(`Moved to Trash — <button class="cpbtn" onclick="Trash.restore('${S.trash[S.trash.length-1].id}');this.closest('.toast').remove()">Undo</button>`,'info',6000);}
};
