const Sims={
  render(){
    const f=S.simF;const q=(document.getElementById('simQ')?.value||'').toLowerCase();const sort=document.getElementById('simSort')?.value||'network';
    const chips=[['all','All'],['physical','📱 Physical'],['esim','📡 eSIM'],['active','✅ Active'],['backup','💤 Backup']];
    const ci=document.getElementById('simChips');if(ci)ci.innerHTML=chips.map(([v,l])=>`<div class="chip${v===f?' on':''}" onclick="S.simF='${v}';Sims.render()">${l}</div>`).join('');
    let data=S.sims.filter(s=>{if(['PK','GB','AE','US'].includes(f)&&s.country!==f)return false;if(f==='esim'&&s.simType!=='eSIM')return false;if(f==='active'&&s.status!=='Active')return false;if(f==='backup'&&s.status!=='Backup')return false;return !q||JSON.stringify(s).toLowerCase().includes(q);});
    if(sort==='network')data.sort((a,b)=>a.network.localeCompare(b.network));
    else if(sort==='country')data.sort((a,b)=>a.country.localeCompare(b.country));
    else if(sort==='status')data.sort((a,b)=>a.status.localeCompare(b.status));
    const el=document.getElementById('simItems');if(!el)return;
    if(!data.length){el.innerHTML=`<div class="empty"><div class="empty-ic">📱</div><h3>No SIMs</h3><p>Track all your SIM cards — physical and eSIM</p><button class="btn btn-p" style="margin-top:12px" onclick="Sims.openAdd()">📱 Add SIM Card</button></div>`;return;}
    const byCC={};data.forEach(s=>{(byCC[s.country||'OTHER']=byCC[s.country||'OTHER']||[]).push(s);});
    el.innerHTML=Object.entries(byCC).map(([cc,items])=>`<div><div class="csec-h"><span style="font-size:18px">${U.flag(cc)}</span><span class="csec-name">${U.cname(cc)}</span><span class="csec-cnt">${items.length}</span></div>${items.map(s=>{const st={Active:'b-ok',Backup:'b-warn',Inactive:'b-err','Lost/Stolen':'b-err'};return `<div class="entry"><div class="entry-main"><div class="entry-ic">${s.simType==='eSIM'?'📡':'📱'}</div><div class="entry-body"><div class="entry-name">${s.network}</div><div class="entry-sub">${s.phone?s.phone.replace(/(\+\d{2,3})[\d\s]{4,}/,'$1 *** ***'):'No number'} · ${s.simType||'Physical'}</div><div class="entry-meta"><span class="badge ${st[s.status]||'b-muted'}">${s.status}</span>${s.dataPlan?`<span class="badge b-muted">${s.dataPlan}GB</span>`:''} ${s.rechargeReminder&&s.nextRecharge?`<span class="badge b-warn">🔋 ${s.nextRecharge}</span>`:''} ${s.wallet?`<span class="badge b-acc">💳 ${s.wallet}</span>`:''}</div></div><div class="entry-acts"><button class="icb fav${s.favorite?' on':''}" onclick="Sims.fav('${s.id}')">⭐</button><button class="icb" onclick="Sims.detail('${s.id}')">👁️</button><button class="icb" onclick="Sims.edit('${s.id}')">✏️</button><button class="icb del" onclick="Sims.del('${s.id}')">🗑️</button></div></div></div>`;}).join('')}</div>`).join('');
  },
  openAdd(){Modal.open('📱 Add SIM',this.form(),`<button class="btn btn-g" onclick="Modal.close()">Cancel</button><button class="btn btn-p" onclick="Sims.save()">Save</button>`);this.bindCC();},
  form(s={}){return `<datalist id="netDL">${U.netOpts(s.country||'')}</datalist>
    <div class="fr"><div class="fg"><label class="fl">Country *</label><select class="inp" id="sf-cc">${U.countries()}</select></div><div class="fg"><label class="fl">Network *</label><input class="inp" id="sf-net" value="${s.network||''}" list="netDL" placeholder="Jazz, O2..."></div></div>
    <div class="fr"><div class="fg"><label class="fl">Type</label><datalist id="sfTypeDL"><option>Physical</option><option>eSIM</option><option>Dual SIM</option></datalist><input class="inp" id="sf-type" value="${s.simType||''}" list="sfTypeDL" placeholder="Physical, eSIM..."></div><div class="fg"><label class="fl">Status</label><datalist id="sfStatusDL"><option>Active</option><option>Backup</option><option>Inactive</option><option>Lost/Stolen</option><option>Roaming</option></datalist><input class="inp" id="sf-status" value="${s.status||''}" list="sfStatusDL" placeholder="Active, Backup..."></div></div>
    <div class="fg"><label class="fl">Phone Number</label><div style="display:flex;gap:8px"><span id="sf-pfx" style="display:flex;align-items:center;padding:0 11px;background:var(--glass2);border:1px solid var(--border);border-radius:var(--rsm);font-size:13px;flex-shrink:0;white-space:nowrap">${U.phone(s.country||'')}</span><input class="inp" id="sf-phone" value="${s.phone?s.phone.replace(/^\+\d+\s?/,''):''}" placeholder="300 1234567" style="flex:1"></div></div>
    <div class="fr"><div class="fg"><label class="fl">Data Plan (GB)</label><input class="inp" id="sf-data" value="${s.dataPlan||''}" type="number" placeholder="10"></div><div class="fg"><label class="fl">Balance</label><input class="inp" id="sf-bal" value="${s.balance||''}" placeholder="Rs.500"></div></div>
    <div class="fr"><div class="fg"><label class="fl">SIM PIN</label><input class="inp" id="sf-pin" value="${s.simPin||''}" type="password" maxlength="8" inputmode="numeric" placeholder="••••"></div><div class="fg"><label class="fl">PUK Code</label><input class="inp" id="sf-puk" value="${s.pukCode||''}" type="password" placeholder="PUK"></div></div>
    <div class="fr"><div class="fg"><label class="fl">Linked Wallet</label><input class="inp" id="sf-wal" value="${s.wallet||''}" placeholder="JazzCash..."></div><div class="fg"><label class="fl">Registered Name</label><input class="inp" id="sf-rname" value="${s.regName||S.user.name||''}" placeholder="Owner name"></div></div>
    <div class="fg" style="background:var(--glass);border:1px solid var(--border);border-radius:var(--rsm);padding:12px;margin-top:4px">
      <div style="font-size:11px;font-weight:700;color:var(--text2);margin-bottom:10px">🔋 Recharge Reminder</div>
      <div class="fr"><div class="fg"><label class="fl">Next Recharge Date</label><input class="inp" id="sf-rch" value="${s.nextRecharge||''}" type="date"></div><div class="fg" style="justify-content:flex-end;padding-top:18px"><label style="display:flex;align-items:center;gap:8px;cursor:pointer;font-size:13px"><input type="checkbox" id="sf-rem" ${s.rechargeReminder?'checked':""}> Enable</label></div></div>
    </div>
    <div class="fg"><label class="fl">Notes</label><textarea class="inp" id="sf-notes" rows="2">${s.notes||''}</textarea></div>
    <div class="fg"><label class="fl">Tags</label>${U.tags(s.tags||[])}</div>
    <label style="display:flex;align-items:center;gap:7px;cursor:pointer;font-size:13px;margin-top:4px"><input type="checkbox" id="sf-fav" ${s.favorite?'checked':''}> ⭐ Favourite</label>`;},
  bindCC(){setTimeout(()=>{const cc=document.getElementById('sf-cc');if(cc)cc.onchange=()=>{document.getElementById('netDL').innerHTML=U.netOpts(cc.value);const p=document.getElementById('sf-pfx');if(p)p.textContent=U.phone(cc.value);};},60);},
  save(editId=null){const net=document.getElementById('sf-net').value.trim();if(!net){Toast.show('Network required','warning');return;}const cc=document.getElementById('sf-cc').value;const rawPh=document.getElementById('sf-phone').value.trim();const item={id:editId||U.id(),network:net,country:cc,simType:document.getElementById('sf-type').value,status:document.getElementById('sf-status').value,phone:rawPh?(rawPh.startsWith('+')?rawPh:U.phone(cc)+' '+rawPh):'',dataPlan:parseFloat(document.getElementById('sf-data').value)||0,balance:document.getElementById('sf-bal').value.trim(),simPin:document.getElementById('sf-pin').value.trim(),pukCode:document.getElementById('sf-puk').value.trim(),wallet:document.getElementById('sf-wal').value.trim(),regName:document.getElementById('sf-rname').value.trim(),nextRecharge:document.getElementById('sf-rch').value,rechargeReminder:document.getElementById('sf-rem').checked,notes:document.getElementById('sf-notes').value.trim(),tags:U.getTags(),favorite:document.getElementById('sf-fav').checked,createdAt:editId?S.sims.find(x=>x.id===editId)?.createdAt:new Date().toISOString()};if(editId)S.sims=S.sims.map(x=>x.id===editId?item:x);else S.sims.push(item);Activity.log((editId?'Edited':'Added')+' SIM',net);Store.save();Modal.close();this.render();Toast.show(`${editId?'Updated':'Added'}: ${net}`,'success');},
  edit(id){const s=S.sims.find(x=>x.id===id);if(!s)return;Modal.open('✏️ Edit SIM',this.form(s),`<button class="btn btn-g" onclick="Modal.close()">Cancel</button><button class="btn btn-d btn-sm" onclick="Sims.del('${id}',true)">Delete</button><button class="btn btn-p" onclick="Sims.save('${id}')">Update</button>`);setTimeout(()=>{[['sf-cc',s.country||''],['sf-type',s.simType||'Physical'],['sf-status',s.status||'Active']].forEach(([i,v])=>{const e=document.getElementById(i);if(e)e.value=v;});this.bindCC();},60);},
  detail(id){const s=S.sims.find(x=>x.id===id);if(!s)return;Modal.open(`📱 ${s.network}`,`<div>${[['Network',s.network],['Country',U.flag(s.country)+' '+U.cname(s.country)],['Type',s.simType],['Status',s.status],['Phone',s.phone?'••••':'-',s.phone],['SIM PIN',s.simPin?'••••':'-',s.simPin],['PUK',s.pukCode?'••••':'-',s.pukCode],['Data Plan',s.dataPlan?s.dataPlan+'GB':'—'],['Wallet',s.wallet||'—'],['Recharge',s.nextRecharge||'—']].map(([k,v,sec])=>U.drRow(k,v,sec)).join('')}</div>`,`<button class="btn btn-g" onclick="Modal.close()">Close</button><button class="btn btn-p" onclick="Sims.edit('${id}');Modal.close()">Edit</button>`);},
  fav(id){const s=S.sims.find(x=>x.id===id);if(!s)return;s.favorite=!s.favorite;Store.save();this.render();},
  del(id,fm=false){if(!window.__vos_confirm('Delete?'))return;const s=S.sims.find(x=>x.id===id);S.sims=S.sims.filter(x=>x.id!==id);Activity.log('Deleted SIM',s?.network);Store.save();if(fm)Modal.close();this.render();}
};
