const Sims={
  render(){
    const f=S.simF;const q=(document.getElementById('simQ')?.value||'').toLowerCase();const sort=document.getElementById('simSort')?.value||'network';
    const chips=[['all','All','list'],['physical','Physical','smartphone'],['esim','eSIM','smartphone'],['active','Active','target'],['backup','Backup','archive']];
    const ci=document.getElementById('simChips');if(ci)ci.innerHTML=chips.map(([v,l,ic])=>`<div class="chip${v===f?' on':''}" onclick="S.simF='${v}';Sims.render()"><span class="chip-ic">${VC.icon(ic,12)}</span>${l}</div>`).join('');
    let data=S.sims.filter(s=>{if(['PK','GB','AE','US'].includes(f)&&s.country!==f)return false;if(f==='esim'&&s.simType!=='eSIM')return false;if(f==='active'&&s.status!=='Active')return false;if(f==='backup'&&s.status!=='Backup')return false;return !q||JSON.stringify(s).toLowerCase().includes(q);});
    if(sort==='network')data.sort((a,b)=>a.network.localeCompare(b.network));
    else if(sort==='country')data.sort((a,b)=>a.country.localeCompare(b.country));
    else if(sort==='status')data.sort((a,b)=>a.status.localeCompare(b.status));
    const el=document.getElementById('simItems');if(!el)return;
    if(!data.length){el.innerHTML=`<div class="empty-ios"><div class="ei-ic">${VC.icon('smartphone',32)}</div><div class="ei-title">No SIM Cards Yet</div><div class="ei-sub">Track physical SIMs and eSIMs across countries — never lose a number again.</div><div style="display:flex;gap:10px;justify-content:center;margin-top:16px;flex-wrap:wrap"><button type="button" class="btn btn-p" onclick="Sims.openAdd()">+ Add SIM Card</button></div></div>`;return;}
    const byCC={};data.forEach(s=>{(byCC[s.country||'OTHER']=byCC[s.country||'OTHER']||[]).push(s);});
    el.innerHTML=Object.entries(byCC).map(([cc,items])=>`<div><div class="csec-h"><span style="font-size:18px">${U.flag(cc)}</span><span class="csec-name">${escHtml(U.cname(cc))}</span><span class="csec-cnt">${items.length}</span></div>${items.map(s=>{const st={Active:'b-ok',Backup:'b-warn',Inactive:'b-err','Lost/Stolen':'b-err'};return `<div class="entry"><div class="entry-main"><div class="entry-ic">${VC.icon(s.simType==='eSIM'?'smartphone':'smartphone',18)}</div><div class="entry-body"><div class="entry-name">${escHtml(s.network)}</div><div class="entry-sub">${s.phone?s.phone.replace(/(\+\d{2,3})[\d\s]{4,}/,'$1 *** ***'):'No number'} · ${escHtml(s.simType||'Physical')}</div><div class="entry-meta"><span class="badge ${st[s.status]||'b-muted'}">${escHtml(s.status)}</span>${s.dataPlan?`<span class="badge b-muted">${escHtml(s.dataPlan)}GB</span>`:''} ${s.rechargeReminder&&s.nextRecharge?`<span class="badge b-warn">Recharge ${escHtml(s.nextRecharge)}</span>`:''} ${s.contractEnd&&(s.contractReminder!==false)?`<span class="badge b-warn">Contract ${escHtml(s.contractEnd)}</span>`:''} ${s.wallet?`<span class="badge b-acc">${escHtml(s.wallet)}</span>`:''}</div></div><div class="entry-acts">${U.icb('star',{onclick:`Sims.fav('${s.id}')`,class:'fav'+(s.favorite?' on':'')})}${U.actsViewEditDel('Sims', s.id)}</div></div></div>`;}).join('')}</div>`).join('');
  },
  openAdd(){Modal.open('Add SIM',this.form(),`<button type="button" class="btn btn-g" onclick="Modal.close()">Cancel</button><button type="button" class="btn btn-p" onclick="Sims.save()">Save</button>`);this.bindCC();},
  form(s={}){
    const simNames=SMART_DB.sims.map(x=>`<option value="${escAttr(x.network)}">`).join('');
    const hasExtra=!!(s.simPin||s.pukCode||s.dataPlan||s.balance||s.nextRecharge||s.contractEnd||s.wallet||s.regName||s.notes);
    return `<datalist id="simDL">${simNames}</datalist><datalist id="netDL">${U.netOpts(s.country||'')}</datalist>
    <div class="fr"><div class="fg"><label class="fl">Country *</label><select class="inp" id="sf-cc">${U.countries()}</select></div><div class="fg"><label class="fl">Network *</label><input class="inp" id="sf-net" value="${escAttr(s.network||'')}" list="simDL" placeholder="Jazz, O2, EE…" oninput="SMART_DB.fillSim(this.value)"></div></div>
    <div class="fg"><label class="fl">Phone Number</label><div style="display:flex;gap:8px"><span id="sf-pfx" style="display:flex;align-items:center;padding:0 11px;background:var(--glass2);border:1px solid var(--border);border-radius:var(--rsm);font-size:13px;flex-shrink:0;white-space:nowrap">${U.phone(s.country||'')}</span><input class="inp" id="sf-phone" value="${escAttr(s.phone?s.phone.replace(/^\+\d+\s?/,''):'')}" placeholder="300 1234567" style="flex:1"></div></div>
    <details${hasExtra?' open':''} style="margin-top:10px">
      <summary style="cursor:pointer;font-size:12px;font-weight:700;color:var(--text2);padding:6px 0;list-style:none;display:flex;align-items:center;gap:6px"><span style="flex:1">More details</span><span style="font-size:10px;color:var(--text3)">▾</span></summary>
      <div style="padding-top:10px">
        <div class="fr"><div class="fg"><label class="fl">Type</label><datalist id="sfTypeDL"><option>Physical</option><option>eSIM</option><option>Dual SIM</option></datalist><input class="inp" id="sf-type" value="${escAttr(s.simType||'')}" list="sfTypeDL" placeholder="Physical, eSIM..."></div><div class="fg"><label class="fl">Status</label><datalist id="sfStatusDL"><option>Active</option><option>Backup</option><option>Inactive</option><option>Lost/Stolen</option><option>Roaming</option></datalist><input class="inp" id="sf-status" value="${escAttr(s.status||'')}" list="sfStatusDL" placeholder="Active, Backup..."></div></div>
        <div class="fr"><div class="fg"><label class="fl">Data Plan (GB)</label><input class="inp" id="sf-data" value="${escAttr(s.dataPlan||'')}" type="number" placeholder="10"></div><div class="fg"><label class="fl">Balance</label><input class="inp" id="sf-bal" value="${escAttr(s.balance||'')}" placeholder="Rs.500"></div></div>
        <div class="fr"><div class="fg"><label class="fl">SIM PIN</label><input class="inp" id="sf-pin" value="${escAttr(s.simPin||'')}" type="password" maxlength="8" inputmode="numeric" placeholder="••••"></div><div class="fg"><label class="fl">PUK Code</label><input class="inp" id="sf-puk" value="${escAttr(s.pukCode||'')}" type="password" placeholder="PUK"></div></div>
        <div class="fr"><div class="fg"><label class="fl">Linked Wallet</label><input class="inp" id="sf-wal" value="${escAttr(s.wallet||'')}" placeholder="JazzCash..."></div><div class="fg"><label class="fl">Registered Name</label><input class="inp" id="sf-rname" value="${escAttr(s.regName||S.user.name||'')}" placeholder="Owner name"></div></div>
        <div class="fg" style="background:var(--glass);border:1px solid var(--border);border-radius:var(--rsm);padding:12px;margin-top:4px">
          <div style="font-size:11px;font-weight:700;color:var(--text2);margin-bottom:10px">Recharge Reminder</div>
          <div class="fr"><div class="fg"><label class="fl">Next Recharge Date</label><input class="inp" id="sf-rch" value="${escAttr(s.nextRecharge||'')}" type="date"></div><div class="fg" style="justify-content:flex-end;padding-top:18px"><label style="display:flex;align-items:center;gap:8px;cursor:pointer;font-size:13px"><input type="checkbox" id="sf-rem" ${s.rechargeReminder?'checked':''}> Enable</label></div></div>
        </div>
        <div class="fg" style="background:var(--glass);border:1px solid var(--border);border-radius:var(--rsm);padding:12px;margin-top:4px">
          <div style="font-size:11px;font-weight:700;color:var(--text2);margin-bottom:10px">Contract / Plan Expiry</div>
          <div class="fr"><div class="fg"><label class="fl">Contract End Date</label><input class="inp" id="sf-contract" value="${escAttr(s.contractEnd||'')}" type="date"></div><div class="fg" style="justify-content:flex-end;padding-top:18px"><label style="display:flex;align-items:center;gap:8px;cursor:pointer;font-size:13px"><input type="checkbox" id="sf-contract-rem" ${s.contractReminder!==false?'checked':''}> Alert</label></div></div>
        </div>
        <div class="fg"><label class="fl">Notes</label><textarea class="inp" id="sf-notes" rows="2">${escAttr(s.notes||'')}</textarea></div>
        <div class="fg"><label class="fl">Tags</label>${U.tags(s.tags||[])}</div>
        <label style="display:flex;align-items:center;gap:7px;cursor:pointer;font-size:13px;margin-top:4px"><input type="checkbox" id="sf-fav" ${s.favorite?'checked':''}> Favourite</label>
      </div>
    </details>`;},
  bindCC(){setTimeout(()=>{const cc=document.getElementById('sf-cc');if(cc)cc.onchange=()=>{document.getElementById('netDL').innerHTML=U.netOpts(cc.value);const p=document.getElementById('sf-pfx');if(p)p.textContent=U.phone(cc.value);};},60);},
  save(editId=null){const net=document.getElementById('sf-net').value.trim();if(!net){Toast.show('Network required','warning');return;}const cc=document.getElementById('sf-cc').value;const rawPh=document.getElementById('sf-phone').value.trim();if(!editId){const dup=checkDuplicate('sim',{network:net,phone:rawPh?(rawPh.startsWith('+')?rawPh:U.phone(cc)+' '+rawPh):''});if(dup.isDuplicate&&!window.__vos_confirm(dup.message))return;}const nextRch=document.getElementById('sf-rch')?.value||'';const contractEnd=document.getElementById('sf-contract')?.value||'';const item={id:editId||U.id(),network:net,country:cc,simType:document.getElementById('sf-type')?.value||'Physical',status:document.getElementById('sf-status')?.value||'Active',phone:rawPh?(rawPh.startsWith('+')?rawPh:U.phone(cc)+' '+rawPh):'',dataPlan:parseFloat(document.getElementById('sf-data')?.value)||0,balance:document.getElementById('sf-bal')?.value.trim()||'',simPin:document.getElementById('sf-pin')?.value.trim()||'',pukCode:document.getElementById('sf-puk')?.value.trim()||'',wallet:document.getElementById('sf-wal')?.value.trim()||'',regName:document.getElementById('sf-rname')?.value.trim()||'',nextRecharge:nextRch,rechargeReminder:document.getElementById('sf-rem')?.checked||false,contractEnd,contractReminder:document.getElementById('sf-contract-rem')?.checked!==false,notes:document.getElementById('sf-notes')?.value.trim()||'',tags:U.getTags(),favorite:document.getElementById('sf-fav')?.checked||false,createdAt:editId?S.sims.find(x=>x.id===editId)?.createdAt:new Date().toISOString()};const simAuto=autoTags('sim',item);item.tags=[...new Set([...(item.tags||[]),...simAuto])];if(editId)S.sims=S.sims.map(x=>x.id===editId?item:x);else S.sims.push(item);if(typeof autoLink==='function')autoLink('sim',item);Activity.log((editId?'Edited':'Added')+' SIM',net);Store.save();Modal.close();this.render();Toast.show(`${editId?'Updated':'Added'}: ${net}`,'success');
    if(!editId&&!nextRch){setTimeout(()=>{const bar=document.createElement('div');bar.style.cssText='position:fixed;bottom:calc(var(--tabh) + env(safe-area-inset-bottom) + 8px);left:50%;transform:translateX(-50%);background:var(--bg2);border:1px solid var(--border2);border-radius:var(--rfull);padding:10px 18px;display:flex;align-items:center;gap:12px;z-index:9999;box-shadow:var(--shadowlg);animation:slideIn .25s var(--spring);white-space:nowrap';bar.innerHTML=`<span style="font-size:13px;color:var(--text2)">Set recharge reminder?</span><button type="button" class="btn btn-p btn-sm" onclick="this.closest('div').remove();Sims.edit('${item.id}')">Set</button><button type="button" class="btn btn-g btn-sm" onclick="this.closest('div').remove()">Skip</button>`;document.body.appendChild(bar);setTimeout(()=>{if(bar.isConnected)bar.remove();},7000);},300);}
    if(!editId)promptAddAnother('SIM','Sims.openAdd');},
  edit(id){const s=S.sims.find(x=>x.id===id);if(!s)return;Modal.open('Edit SIM',this.form(s),`<button type="button" class="btn btn-g" onclick="Modal.close()">Cancel</button><button type="button" class="btn btn-d btn-sm" onclick="Sims.del('${id}',true)">Delete</button><button type="button" class="btn btn-p" onclick="Sims.save('${id}')">Update</button>`);setTimeout(()=>{[['sf-cc',s.country||''],['sf-type',s.simType||'Physical'],['sf-status',s.status||'Active']].forEach(([i,v])=>{const e=document.getElementById(i);if(e)e.value=v;});this.bindCC();},60);},
  detail(id){const s=S.sims.find(x=>x.id===id);if(!s)return;Modal.open(`${s.network}`,`<div>${[['Network',s.network],['Country',U.flag(s.country)+' '+U.cname(s.country)],['Type',s.simType],['Status',s.status],['Phone',s.phone?'••••':'-',s.phone],['SIM PIN',s.simPin?'••••':'-',s.simPin],['PUK',s.pukCode?'••••':'-',s.pukCode],['Data Plan',s.dataPlan?s.dataPlan+'GB':'—'],['Wallet',s.wallet||'—'],['Recharge',s.nextRecharge||'—'],['Contract End',s.contractEnd||'—']].map(([k,v,sec])=>U.drRow(k,v,sec)).join('')}</div>`,`<button type="button" class="btn btn-g" onclick="Modal.close()">Close</button><button type="button" class="btn btn-p" onclick="Sims.edit('${id}');Modal.close()">Edit</button>`);},
  fav(id){const s=S.sims.find(x=>x.id===id);if(!s)return;s.favorite=!s.favorite;Store.save();this.render();},
  del(id,fm=false){if(!window.__vos_confirm('Move to Trash?'))return;const s=S.sims.find(x=>x.id===id);if(!s)return;S.trash.push({id:U.id(),type:'sims',data:s,deletedAt:new Date().toISOString()});S.sims=S.sims.filter(x=>x.id!==id);Activity.log('Trashed SIM',s.network);Store.save();if(fm)Modal.close();this.render();Toast.show(`Moved to Trash — <button type="button" class="cpbtn" onclick="Trash.restore('${S.trash[S.trash.length-1].id}');this.closest('.toast').remove()">Undo</button>`,'info',6000);}
};
